// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CandidatesColumns holds the columns for the "candidates" table.
	CandidatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "vector", Type: field.TypeString},
		{Name: "digest", Type: field.TypeString},
		{Name: "checks", Type: field.TypeString},
		{Name: "deliverables", Type: field.TypeString, Default: "[]"},
		{Name: "status", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeFloat64},
		{Name: "task_id", Type: field.TypeString},
	}
	// CandidatesTable holds the schema information for the "candidates" table.
	CandidatesTable = &schema.Table{
		Name:       "candidates",
		Columns:    CandidatesColumns,
		PrimaryKey: []*schema.Column{CandidatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "candidates_tasks_candidates",
				Columns:    []*schema.Column{CandidatesColumns[7]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CheckpointsColumns holds the columns for the "checkpoints" table.
	CheckpointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "archive_path", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeFloat64},
		{Name: "session_id", Type: field.TypeString},
		{Name: "task_id", Type: field.TypeString, Nullable: true},
	}
	// CheckpointsTable holds the schema information for the "checkpoints" table.
	CheckpointsTable = &schema.Table{
		Name:       "checkpoints",
		Columns:    CheckpointsColumns,
		PrimaryKey: []*schema.Column{CheckpointsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "checkpoints_sessions_checkpoints",
				Columns:    []*schema.Column{CheckpointsColumns[4]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "checkpoints_tasks_checkpoints",
				Columns:    []*schema.Column{CheckpointsColumns[5]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "sequence", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeFloat64},
		{Name: "session_id", Type: field.TypeString},
		{Name: "task_id", Type: field.TypeString, Nullable: true},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_sessions_events",
				Columns:    []*schema.Column{EventsColumns[4]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "events_tasks_events",
				Columns:    []*schema.Column{EventsColumns[5]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// InvocationsColumns holds the columns for the "invocations" table.
	InvocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "runtime", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "sandbox_backend", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "exit_code", Type: field.TypeInt, Nullable: true},
		{Name: "native_id", Type: field.TypeString, Nullable: true},
		{Name: "log_path", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeFloat64},
		{Name: "ended_at", Type: field.TypeFloat64, Nullable: true},
		{Name: "turn_id", Type: field.TypeString},
	}
	// InvocationsTable holds the schema information for the "invocations" table.
	InvocationsTable = &schema.Table{
		Name:       "invocations",
		Columns:    InvocationsColumns,
		PrimaryKey: []*schema.Column{InvocationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invocations_turns_invocations",
				Columns:    []*schema.Column{InvocationsColumns[10]},
				RefColumns: []*schema.Column{TurnsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "spec", Type: field.TypeString},
		{Name: "environment", Type: field.TypeString},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true},
		{Name: "creation_digest", Type: field.TypeString, Nullable: true},
		{Name: "environment_digest", Type: field.TypeString},
		{Name: "workspace", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "native_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeFloat64},
		{Name: "completed_at", Type: field.TypeFloat64, Nullable: true},
		{Name: "cancelled_at", Type: field.TypeFloat64, Nullable: true},
		{Name: "cancel_reason", Type: field.TypeString, Nullable: true},
		{Name: "parent_session_id", Type: field.TypeString, Nullable: true},
		{Name: "parent_task_id", Type: field.TypeString, Nullable: true},
		{Name: "parent_invocation_id", Type: field.TypeString, Nullable: true},
		{Name: "delegate_agent_id", Type: field.TypeString, Nullable: true},
		{Name: "delegation_request_digest", Type: field.TypeString, Nullable: true},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{SessionsColumns[3]},
			},
			{
				Name:    "session_parent_task_id",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[14]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "sequence", Type: field.TypeInt},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "spec", Type: field.TypeString},
		{Name: "spec_digest", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "candidate_id", Type: field.TypeString, Nullable: true},
		{Name: "error_code", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeFloat64},
		{Name: "session_id", Type: field.TypeString},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_sessions_tasks",
				Columns:    []*schema.Column{TasksColumns[9]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "task_session_id_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{TasksColumns[9], TasksColumns[2]},
			},
			{
				Name:    "task_session_id_sequence",
				Unique:  true,
				Columns: []*schema.Column{TasksColumns[9], TasksColumns[1]},
			},
		},
	}
	// TaskBasesColumns holds the columns for the "task_bases" table.
	TaskBasesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "repo_id", Type: field.TypeString},
		{Name: "base_commit", Type: field.TypeString},
		{Name: "task_id", Type: field.TypeString},
	}
	// TaskBasesTable holds the schema information for the "task_bases" table.
	TaskBasesTable = &schema.Table{
		Name:       "task_bases",
		Columns:    TaskBasesColumns,
		PrimaryKey: []*schema.Column{TaskBasesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_bases_tasks_bases",
				Columns:    []*schema.Column{TaskBasesColumns[3]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taskbase_task_id_repo_id",
				Unique:  true,
				Columns: []*schema.Column{TaskBasesColumns[3], TaskBasesColumns[1]},
			},
		},
	}
	// TurnsColumns holds the columns for the "turns" table.
	TurnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "sequence", Type: field.TypeInt},
		{Name: "input", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "invocation_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeFloat64},
		{Name: "task_id", Type: field.TypeString},
	}
	// TurnsTable holds the schema information for the "turns" table.
	TurnsTable = &schema.Table{
		Name:       "turns",
		Columns:    TurnsColumns,
		PrimaryKey: []*schema.Column{TurnsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "turns_tasks_turns",
				Columns:    []*schema.Column{TurnsColumns[6]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "turn_task_id_sequence",
				Unique:  true,
				Columns: []*schema.Column{TurnsColumns[6], TurnsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CandidatesTable,
		CheckpointsTable,
		EventsTable,
		InvocationsTable,
		SessionsTable,
		TasksTable,
		TaskBasesTable,
		TurnsTable,
	}
)

func init() {
	CandidatesTable.ForeignKeys[0].RefTable = TasksTable
	CandidatesTable.Annotation = &entsql.Annotation{
		Table: "candidates",
	}
	CheckpointsTable.ForeignKeys[0].RefTable = SessionsTable
	CheckpointsTable.ForeignKeys[1].RefTable = TasksTable
	CheckpointsTable.Annotation = &entsql.Annotation{
		Table: "checkpoints",
	}
	EventsTable.ForeignKeys[0].RefTable = SessionsTable
	EventsTable.ForeignKeys[1].RefTable = TasksTable
	EventsTable.Annotation = &entsql.Annotation{
		Table: "events",
	}
	InvocationsTable.ForeignKeys[0].RefTable = TurnsTable
	InvocationsTable.Annotation = &entsql.Annotation{
		Table: "invocations",
	}
	SessionsTable.Annotation = &entsql.Annotation{
		Table: "sessions",
	}
	TasksTable.ForeignKeys[0].RefTable = SessionsTable
	TasksTable.Annotation = &entsql.Annotation{
		Table: "tasks",
	}
	TaskBasesTable.ForeignKeys[0].RefTable = TasksTable
	TaskBasesTable.Annotation = &entsql.Annotation{
		Table: "task_bases",
	}
	TurnsTable.ForeignKeys[0].RefTable = TasksTable
	TurnsTable.Annotation = &entsql.Annotation{
		Table: "turns",
	}
}
