// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Covalane/turnyard/internal/store/ent/candidate"
	"github.com/Covalane/turnyard/internal/store/ent/task"
)

// Candidate is the model entity for the Candidate schema.
type Candidate struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// Vector holds the value of the "vector" field.
	Vector string `json:"vector,omitempty"`
	// Digest holds the value of the "digest" field.
	Digest string `json:"digest,omitempty"`
	// Checks holds the value of the "checks" field.
	Checks string `json:"checks,omitempty"`
	// Deliverables holds the value of the "deliverables" field.
	Deliverables string `json:"deliverables,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt float64 `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CandidateQuery when eager-loading is set.
	Edges        CandidateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CandidateEdges holds the relations/edges for other nodes in the graph.
type CandidateEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CandidateEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Candidate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case candidate.FieldCreatedAt:
			values[i] = new(sql.NullFloat64)
		case candidate.FieldID, candidate.FieldTaskID, candidate.FieldVector, candidate.FieldDigest, candidate.FieldChecks, candidate.FieldDeliverables, candidate.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Candidate fields.
func (_m *Candidate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case candidate.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case candidate.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case candidate.FieldVector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vector", values[i])
			} else if value.Valid {
				_m.Vector = value.String
			}
		case candidate.FieldDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field digest", values[i])
			} else if value.Valid {
				_m.Digest = value.String
			}
		case candidate.FieldChecks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checks", values[i])
			} else if value.Valid {
				_m.Checks = value.String
			}
		case candidate.FieldDeliverables:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deliverables", values[i])
			} else if value.Valid {
				_m.Deliverables = value.String
			}
		case candidate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case candidate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Candidate.
// This includes values selected through modifiers, order, etc.
func (_m *Candidate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Candidate entity.
func (_m *Candidate) QueryTask() *TaskQuery {
	return NewCandidateClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this Candidate.
// Note that you need to call Candidate.Unwrap() before calling this method if this Candidate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Candidate) Update() *CandidateUpdateOne {
	return NewCandidateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Candidate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Candidate) Unwrap() *Candidate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Candidate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Candidate) String() string {
	var builder strings.Builder
	builder.WriteString("Candidate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("vector=")
	builder.WriteString(_m.Vector)
	builder.WriteString(", ")
	builder.WriteString("digest=")
	builder.WriteString(_m.Digest)
	builder.WriteString(", ")
	builder.WriteString("checks=")
	builder.WriteString(_m.Checks)
	builder.WriteString(", ")
	builder.WriteString("deliverables=")
	builder.WriteString(_m.Deliverables)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteByte(')')
	return builder.String()
}

// Candidates is a parsable slice of Candidate.
type Candidates []*Candidate
