// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/candidate"
	"github.com/Covalane/turnyard/internal/store/ent/task"
)

// CandidateCreate is the builder for creating a Candidate entity.
type CandidateCreate struct {
	config
	mutation *CandidateMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *CandidateCreate) SetTaskID(v string) *CandidateCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetVector sets the "vector" field.
func (_c *CandidateCreate) SetVector(v string) *CandidateCreate {
	_c.mutation.SetVector(v)
	return _c
}

// SetDigest sets the "digest" field.
func (_c *CandidateCreate) SetDigest(v string) *CandidateCreate {
	_c.mutation.SetDigest(v)
	return _c
}

// SetChecks sets the "checks" field.
func (_c *CandidateCreate) SetChecks(v string) *CandidateCreate {
	_c.mutation.SetChecks(v)
	return _c
}

// SetDeliverables sets the "deliverables" field.
func (_c *CandidateCreate) SetDeliverables(v string) *CandidateCreate {
	_c.mutation.SetDeliverables(v)
	return _c
}

// SetNillableDeliverables sets the "deliverables" field if the given value is not nil.
func (_c *CandidateCreate) SetNillableDeliverables(v *string) *CandidateCreate {
	if v != nil {
		_c.SetDeliverables(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CandidateCreate) SetStatus(v string) *CandidateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CandidateCreate) SetCreatedAt(v float64) *CandidateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CandidateCreate) SetID(v string) *CandidateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *CandidateCreate) SetTask(v *Task) *CandidateCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the CandidateMutation object of the builder.
func (_c *CandidateCreate) Mutation() *CandidateMutation {
	return _c.mutation
}

// Save creates the Candidate in the database.
func (_c *CandidateCreate) Save(ctx context.Context) (*Candidate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CandidateCreate) SaveX(ctx context.Context) *Candidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CandidateCreate) defaults() {
	if _, ok := _c.mutation.Deliverables(); !ok {
		v := candidate.DefaultDeliverables
		_c.mutation.SetDeliverables(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CandidateCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "Candidate.task_id"`)}
	}
	if _, ok := _c.mutation.Vector(); !ok {
		return &ValidationError{Name: "vector", err: errors.New(`ent: missing required field "Candidate.vector"`)}
	}
	if _, ok := _c.mutation.Digest(); !ok {
		return &ValidationError{Name: "digest", err: errors.New(`ent: missing required field "Candidate.digest"`)}
	}
	if _, ok := _c.mutation.Checks(); !ok {
		return &ValidationError{Name: "checks", err: errors.New(`ent: missing required field "Candidate.checks"`)}
	}
	if _, ok := _c.mutation.Deliverables(); !ok {
		return &ValidationError{Name: "deliverables", err: errors.New(`ent: missing required field "Candidate.deliverables"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Candidate.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Candidate.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "Candidate.task"`)}
	}
	return nil
}

func (_c *CandidateCreate) sqlSave(ctx context.Context) (*Candidate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Candidate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CandidateCreate) createSpec() (*Candidate, *sqlgraph.CreateSpec) {
	var (
		_node = &Candidate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(candidate.Table, sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Vector(); ok {
		_spec.SetField(candidate.FieldVector, field.TypeString, value)
		_node.Vector = value
	}
	if value, ok := _c.mutation.Digest(); ok {
		_spec.SetField(candidate.FieldDigest, field.TypeString, value)
		_node.Digest = value
	}
	if value, ok := _c.mutation.Checks(); ok {
		_spec.SetField(candidate.FieldChecks, field.TypeString, value)
		_node.Checks = value
	}
	if value, ok := _c.mutation.Deliverables(); ok {
		_spec.SetField(candidate.FieldDeliverables, field.TypeString, value)
		_node.Deliverables = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(candidate.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(candidate.FieldCreatedAt, field.TypeFloat64, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   candidate.TaskTable,
			Columns: []string{candidate.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CandidateCreateBulk is the builder for creating many Candidate entities in bulk.
type CandidateCreateBulk struct {
	config
	err      error
	builders []*CandidateCreate
}

// Save creates the Candidate entities in the database.
func (_c *CandidateCreateBulk) Save(ctx context.Context) ([]*Candidate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Candidate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CandidateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CandidateCreateBulk) SaveX(ctx context.Context) []*Candidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
