// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/checkpoint"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
	"github.com/Covalane/turnyard/internal/store/ent/session"
	"github.com/Covalane/turnyard/internal/store/ent/task"
)

// CheckpointUpdate is the builder for updating Checkpoint entities.
type CheckpointUpdate struct {
	config
	hooks    []Hook
	mutation *CheckpointMutation
}

// Where appends a list predicates to the CheckpointUpdate builder.
func (_u *CheckpointUpdate) Where(ps ...predicate.Checkpoint) *CheckpointUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *CheckpointUpdate) SetSessionID(v string) *CheckpointUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *CheckpointUpdate) SetNillableSessionID(v *string) *CheckpointUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *CheckpointUpdate) SetTaskID(v string) *CheckpointUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *CheckpointUpdate) SetNillableTaskID(v *string) *CheckpointUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *CheckpointUpdate) ClearTaskID() *CheckpointUpdate {
	_u.mutation.ClearTaskID()
	return _u
}

// SetArchivePath sets the "archive_path" field.
func (_u *CheckpointUpdate) SetArchivePath(v string) *CheckpointUpdate {
	_u.mutation.SetArchivePath(v)
	return _u
}

// SetNillableArchivePath sets the "archive_path" field if the given value is not nil.
func (_u *CheckpointUpdate) SetNillableArchivePath(v *string) *CheckpointUpdate {
	if v != nil {
		_u.SetArchivePath(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *CheckpointUpdate) SetMetadata(v string) *CheckpointUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *CheckpointUpdate) SetNillableMetadata(v *string) *CheckpointUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CheckpointUpdate) SetCreatedAt(v float64) *CheckpointUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CheckpointUpdate) SetNillableCreatedAt(v *float64) *CheckpointUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *CheckpointUpdate) AddCreatedAt(v float64) *CheckpointUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *CheckpointUpdate) SetSession(v *Session) *CheckpointUpdate {
	return _u.SetSessionID(v.ID)
}

// SetTask sets the "task" edge to the Task entity.
func (_u *CheckpointUpdate) SetTask(v *Task) *CheckpointUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the CheckpointMutation object of the builder.
func (_u *CheckpointUpdate) Mutation() *CheckpointMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *CheckpointUpdate) ClearSession() *CheckpointUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *CheckpointUpdate) ClearTask() *CheckpointUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckpointUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckpointUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckpointUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckpointUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckpointUpdate) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkpoint.session"`)
	}
	return nil
}

func (_u *CheckpointUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkpoint.Table, checkpoint.Columns, sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ArchivePath(); ok {
		_spec.SetField(checkpoint.FieldArchivePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(checkpoint.FieldMetadata, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(checkpoint.FieldCreatedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(checkpoint.FieldCreatedAt, field.TypeFloat64, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.SessionTable,
			Columns: []string{checkpoint.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.SessionTable,
			Columns: []string{checkpoint.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.TaskTable,
			Columns: []string{checkpoint.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.TaskTable,
			Columns: []string{checkpoint.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckpointUpdateOne is the builder for updating a single Checkpoint entity.
type CheckpointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckpointMutation
}

// SetSessionID sets the "session_id" field.
func (_u *CheckpointUpdateOne) SetSessionID(v string) *CheckpointUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *CheckpointUpdateOne) SetNillableSessionID(v *string) *CheckpointUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *CheckpointUpdateOne) SetTaskID(v string) *CheckpointUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *CheckpointUpdateOne) SetNillableTaskID(v *string) *CheckpointUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *CheckpointUpdateOne) ClearTaskID() *CheckpointUpdateOne {
	_u.mutation.ClearTaskID()
	return _u
}

// SetArchivePath sets the "archive_path" field.
func (_u *CheckpointUpdateOne) SetArchivePath(v string) *CheckpointUpdateOne {
	_u.mutation.SetArchivePath(v)
	return _u
}

// SetNillableArchivePath sets the "archive_path" field if the given value is not nil.
func (_u *CheckpointUpdateOne) SetNillableArchivePath(v *string) *CheckpointUpdateOne {
	if v != nil {
		_u.SetArchivePath(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *CheckpointUpdateOne) SetMetadata(v string) *CheckpointUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *CheckpointUpdateOne) SetNillableMetadata(v *string) *CheckpointUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CheckpointUpdateOne) SetCreatedAt(v float64) *CheckpointUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CheckpointUpdateOne) SetNillableCreatedAt(v *float64) *CheckpointUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *CheckpointUpdateOne) AddCreatedAt(v float64) *CheckpointUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *CheckpointUpdateOne) SetSession(v *Session) *CheckpointUpdateOne {
	return _u.SetSessionID(v.ID)
}

// SetTask sets the "task" edge to the Task entity.
func (_u *CheckpointUpdateOne) SetTask(v *Task) *CheckpointUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the CheckpointMutation object of the builder.
func (_u *CheckpointUpdateOne) Mutation() *CheckpointMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *CheckpointUpdateOne) ClearSession() *CheckpointUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *CheckpointUpdateOne) ClearTask() *CheckpointUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the CheckpointUpdate builder.
func (_u *CheckpointUpdateOne) Where(ps ...predicate.Checkpoint) *CheckpointUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckpointUpdateOne) Select(field string, fields ...string) *CheckpointUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Checkpoint entity.
func (_u *CheckpointUpdateOne) Save(ctx context.Context) (*Checkpoint, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckpointUpdateOne) SaveX(ctx context.Context) *Checkpoint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckpointUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckpointUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckpointUpdateOne) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkpoint.session"`)
	}
	return nil
}

func (_u *CheckpointUpdateOne) sqlSave(ctx context.Context) (_node *Checkpoint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkpoint.Table, checkpoint.Columns, sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Checkpoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkpoint.FieldID)
		for _, f := range fields {
			if !checkpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ArchivePath(); ok {
		_spec.SetField(checkpoint.FieldArchivePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(checkpoint.FieldMetadata, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(checkpoint.FieldCreatedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(checkpoint.FieldCreatedAt, field.TypeFloat64, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.SessionTable,
			Columns: []string{checkpoint.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.SessionTable,
			Columns: []string{checkpoint.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.TaskTable,
			Columns: []string{checkpoint.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkpoint.TaskTable,
			Columns: []string{checkpoint.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Checkpoint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
