// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Covalane/turnyard/internal/store/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Covalane/turnyard/internal/store/ent/candidate"
	"github.com/Covalane/turnyard/internal/store/ent/checkpoint"
	"github.com/Covalane/turnyard/internal/store/ent/event"
	"github.com/Covalane/turnyard/internal/store/ent/invocation"
	"github.com/Covalane/turnyard/internal/store/ent/session"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/taskbase"
	"github.com/Covalane/turnyard/internal/store/ent/turn"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Candidate is the client for interacting with the Candidate builders.
	Candidate *CandidateClient
	// Checkpoint is the client for interacting with the Checkpoint builders.
	Checkpoint *CheckpointClient
	// Event is the client for interacting with the Event builders.
	Event *EventClient
	// Invocation is the client for interacting with the Invocation builders.
	Invocation *InvocationClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// TaskBase is the client for interacting with the TaskBase builders.
	TaskBase *TaskBaseClient
	// Turn is the client for interacting with the Turn builders.
	Turn *TurnClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Candidate = NewCandidateClient(c.config)
	c.Checkpoint = NewCheckpointClient(c.config)
	c.Event = NewEventClient(c.config)
	c.Invocation = NewInvocationClient(c.config)
	c.Session = NewSessionClient(c.config)
	c.Task = NewTaskClient(c.config)
	c.TaskBase = NewTaskBaseClient(c.config)
	c.Turn = NewTurnClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Candidate:  NewCandidateClient(cfg),
		Checkpoint: NewCheckpointClient(cfg),
		Event:      NewEventClient(cfg),
		Invocation: NewInvocationClient(cfg),
		Session:    NewSessionClient(cfg),
		Task:       NewTaskClient(cfg),
		TaskBase:   NewTaskBaseClient(cfg),
		Turn:       NewTurnClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Candidate:  NewCandidateClient(cfg),
		Checkpoint: NewCheckpointClient(cfg),
		Event:      NewEventClient(cfg),
		Invocation: NewInvocationClient(cfg),
		Session:    NewSessionClient(cfg),
		Task:       NewTaskClient(cfg),
		TaskBase:   NewTaskBaseClient(cfg),
		Turn:       NewTurnClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Candidate.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Candidate, c.Checkpoint, c.Event, c.Invocation, c.Session, c.Task, c.TaskBase,
		c.Turn,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Candidate, c.Checkpoint, c.Event, c.Invocation, c.Session, c.Task, c.TaskBase,
		c.Turn,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CandidateMutation:
		return c.Candidate.mutate(ctx, m)
	case *CheckpointMutation:
		return c.Checkpoint.mutate(ctx, m)
	case *EventMutation:
		return c.Event.mutate(ctx, m)
	case *InvocationMutation:
		return c.Invocation.mutate(ctx, m)
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	case *TaskBaseMutation:
		return c.TaskBase.mutate(ctx, m)
	case *TurnMutation:
		return c.Turn.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CandidateClient is a client for the Candidate schema.
type CandidateClient struct {
	config
}

// NewCandidateClient returns a client for the Candidate from the given config.
func NewCandidateClient(c config) *CandidateClient {
	return &CandidateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `candidate.Hooks(f(g(h())))`.
func (c *CandidateClient) Use(hooks ...Hook) {
	c.hooks.Candidate = append(c.hooks.Candidate, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `candidate.Intercept(f(g(h())))`.
func (c *CandidateClient) Intercept(interceptors ...Interceptor) {
	c.inters.Candidate = append(c.inters.Candidate, interceptors...)
}

// Create returns a builder for creating a Candidate entity.
func (c *CandidateClient) Create() *CandidateCreate {
	mutation := newCandidateMutation(c.config, OpCreate)
	return &CandidateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Candidate entities.
func (c *CandidateClient) CreateBulk(builders ...*CandidateCreate) *CandidateCreateBulk {
	return &CandidateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CandidateClient) MapCreateBulk(slice any, setFunc func(*CandidateCreate, int)) *CandidateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CandidateCreateBulk{err: fmt.Errorf("calling to CandidateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CandidateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CandidateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Candidate.
func (c *CandidateClient) Update() *CandidateUpdate {
	mutation := newCandidateMutation(c.config, OpUpdate)
	return &CandidateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CandidateClient) UpdateOne(_m *Candidate) *CandidateUpdateOne {
	mutation := newCandidateMutation(c.config, OpUpdateOne, withCandidate(_m))
	return &CandidateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CandidateClient) UpdateOneID(id string) *CandidateUpdateOne {
	mutation := newCandidateMutation(c.config, OpUpdateOne, withCandidateID(id))
	return &CandidateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Candidate.
func (c *CandidateClient) Delete() *CandidateDelete {
	mutation := newCandidateMutation(c.config, OpDelete)
	return &CandidateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CandidateClient) DeleteOne(_m *Candidate) *CandidateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CandidateClient) DeleteOneID(id string) *CandidateDeleteOne {
	builder := c.Delete().Where(candidate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CandidateDeleteOne{builder}
}

// Query returns a query builder for Candidate.
func (c *CandidateClient) Query() *CandidateQuery {
	return &CandidateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCandidate},
		inters: c.Interceptors(),
	}
}

// Get returns a Candidate entity by its id.
func (c *CandidateClient) Get(ctx context.Context, id string) (*Candidate, error) {
	return c.Query().Where(candidate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CandidateClient) GetX(ctx context.Context, id string) *Candidate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a Candidate.
func (c *CandidateClient) QueryTask(_m *Candidate) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(candidate.Table, candidate.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, candidate.TaskTable, candidate.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CandidateClient) Hooks() []Hook {
	return c.hooks.Candidate
}

// Interceptors returns the client interceptors.
func (c *CandidateClient) Interceptors() []Interceptor {
	return c.inters.Candidate
}

func (c *CandidateClient) mutate(ctx context.Context, m *CandidateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CandidateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CandidateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CandidateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CandidateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Candidate mutation op: %q", m.Op())
	}
}

// CheckpointClient is a client for the Checkpoint schema.
type CheckpointClient struct {
	config
}

// NewCheckpointClient returns a client for the Checkpoint from the given config.
func NewCheckpointClient(c config) *CheckpointClient {
	return &CheckpointClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `checkpoint.Hooks(f(g(h())))`.
func (c *CheckpointClient) Use(hooks ...Hook) {
	c.hooks.Checkpoint = append(c.hooks.Checkpoint, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `checkpoint.Intercept(f(g(h())))`.
func (c *CheckpointClient) Intercept(interceptors ...Interceptor) {
	c.inters.Checkpoint = append(c.inters.Checkpoint, interceptors...)
}

// Create returns a builder for creating a Checkpoint entity.
func (c *CheckpointClient) Create() *CheckpointCreate {
	mutation := newCheckpointMutation(c.config, OpCreate)
	return &CheckpointCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Checkpoint entities.
func (c *CheckpointClient) CreateBulk(builders ...*CheckpointCreate) *CheckpointCreateBulk {
	return &CheckpointCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CheckpointClient) MapCreateBulk(slice any, setFunc func(*CheckpointCreate, int)) *CheckpointCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CheckpointCreateBulk{err: fmt.Errorf("calling to CheckpointClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CheckpointCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CheckpointCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Checkpoint.
func (c *CheckpointClient) Update() *CheckpointUpdate {
	mutation := newCheckpointMutation(c.config, OpUpdate)
	return &CheckpointUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CheckpointClient) UpdateOne(_m *Checkpoint) *CheckpointUpdateOne {
	mutation := newCheckpointMutation(c.config, OpUpdateOne, withCheckpoint(_m))
	return &CheckpointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CheckpointClient) UpdateOneID(id string) *CheckpointUpdateOne {
	mutation := newCheckpointMutation(c.config, OpUpdateOne, withCheckpointID(id))
	return &CheckpointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Checkpoint.
func (c *CheckpointClient) Delete() *CheckpointDelete {
	mutation := newCheckpointMutation(c.config, OpDelete)
	return &CheckpointDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CheckpointClient) DeleteOne(_m *Checkpoint) *CheckpointDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CheckpointClient) DeleteOneID(id string) *CheckpointDeleteOne {
	builder := c.Delete().Where(checkpoint.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CheckpointDeleteOne{builder}
}

// Query returns a query builder for Checkpoint.
func (c *CheckpointClient) Query() *CheckpointQuery {
	return &CheckpointQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCheckpoint},
		inters: c.Interceptors(),
	}
}

// Get returns a Checkpoint entity by its id.
func (c *CheckpointClient) Get(ctx context.Context, id string) (*Checkpoint, error) {
	return c.Query().Where(checkpoint.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CheckpointClient) GetX(ctx context.Context, id string) *Checkpoint {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a Checkpoint.
func (c *CheckpointClient) QuerySession(_m *Checkpoint) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(checkpoint.Table, checkpoint.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkpoint.SessionTable, checkpoint.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTask queries the task edge of a Checkpoint.
func (c *CheckpointClient) QueryTask(_m *Checkpoint) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(checkpoint.Table, checkpoint.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkpoint.TaskTable, checkpoint.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CheckpointClient) Hooks() []Hook {
	return c.hooks.Checkpoint
}

// Interceptors returns the client interceptors.
func (c *CheckpointClient) Interceptors() []Interceptor {
	return c.inters.Checkpoint
}

func (c *CheckpointClient) mutate(ctx context.Context, m *CheckpointMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CheckpointCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CheckpointUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CheckpointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CheckpointDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Checkpoint mutation op: %q", m.Op())
	}
}

// EventClient is a client for the Event schema.
type EventClient struct {
	config
}

// NewEventClient returns a client for the Event from the given config.
func NewEventClient(c config) *EventClient {
	return &EventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `event.Hooks(f(g(h())))`.
func (c *EventClient) Use(hooks ...Hook) {
	c.hooks.Event = append(c.hooks.Event, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `event.Intercept(f(g(h())))`.
func (c *EventClient) Intercept(interceptors ...Interceptor) {
	c.inters.Event = append(c.inters.Event, interceptors...)
}

// Create returns a builder for creating a Event entity.
func (c *EventClient) Create() *EventCreate {
	mutation := newEventMutation(c.config, OpCreate)
	return &EventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Event entities.
func (c *EventClient) CreateBulk(builders ...*EventCreate) *EventCreateBulk {
	return &EventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventClient) MapCreateBulk(slice any, setFunc func(*EventCreate, int)) *EventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventCreateBulk{err: fmt.Errorf("calling to EventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Event.
func (c *EventClient) Update() *EventUpdate {
	mutation := newEventMutation(c.config, OpUpdate)
	return &EventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventClient) UpdateOne(_m *Event) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEvent(_m))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventClient) UpdateOneID(id int64) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEventID(id))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Event.
func (c *EventClient) Delete() *EventDelete {
	mutation := newEventMutation(c.config, OpDelete)
	return &EventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventClient) DeleteOne(_m *Event) *EventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventClient) DeleteOneID(id int64) *EventDeleteOne {
	builder := c.Delete().Where(event.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventDeleteOne{builder}
}

// Query returns a query builder for Event.
func (c *EventClient) Query() *EventQuery {
	return &EventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a Event entity by its id.
func (c *EventClient) Get(ctx context.Context, id int64) (*Event, error) {
	return c.Query().Where(event.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventClient) GetX(ctx context.Context, id int64) *Event {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a Event.
func (c *EventClient) QuerySession(_m *Event) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, event.SessionTable, event.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTask queries the task edge of a Event.
func (c *EventClient) QueryTask(_m *Event) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, event.TaskTable, event.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EventClient) Hooks() []Hook {
	return c.hooks.Event
}

// Interceptors returns the client interceptors.
func (c *EventClient) Interceptors() []Interceptor {
	return c.inters.Event
}

func (c *EventClient) mutate(ctx context.Context, m *EventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Event mutation op: %q", m.Op())
	}
}

// InvocationClient is a client for the Invocation schema.
type InvocationClient struct {
	config
}

// NewInvocationClient returns a client for the Invocation from the given config.
func NewInvocationClient(c config) *InvocationClient {
	return &InvocationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invocation.Hooks(f(g(h())))`.
func (c *InvocationClient) Use(hooks ...Hook) {
	c.hooks.Invocation = append(c.hooks.Invocation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invocation.Intercept(f(g(h())))`.
func (c *InvocationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Invocation = append(c.inters.Invocation, interceptors...)
}

// Create returns a builder for creating a Invocation entity.
func (c *InvocationClient) Create() *InvocationCreate {
	mutation := newInvocationMutation(c.config, OpCreate)
	return &InvocationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Invocation entities.
func (c *InvocationClient) CreateBulk(builders ...*InvocationCreate) *InvocationCreateBulk {
	return &InvocationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InvocationClient) MapCreateBulk(slice any, setFunc func(*InvocationCreate, int)) *InvocationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InvocationCreateBulk{err: fmt.Errorf("calling to InvocationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InvocationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InvocationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Invocation.
func (c *InvocationClient) Update() *InvocationUpdate {
	mutation := newInvocationMutation(c.config, OpUpdate)
	return &InvocationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InvocationClient) UpdateOne(_m *Invocation) *InvocationUpdateOne {
	mutation := newInvocationMutation(c.config, OpUpdateOne, withInvocation(_m))
	return &InvocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InvocationClient) UpdateOneID(id string) *InvocationUpdateOne {
	mutation := newInvocationMutation(c.config, OpUpdateOne, withInvocationID(id))
	return &InvocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Invocation.
func (c *InvocationClient) Delete() *InvocationDelete {
	mutation := newInvocationMutation(c.config, OpDelete)
	return &InvocationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InvocationClient) DeleteOne(_m *Invocation) *InvocationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InvocationClient) DeleteOneID(id string) *InvocationDeleteOne {
	builder := c.Delete().Where(invocation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InvocationDeleteOne{builder}
}

// Query returns a query builder for Invocation.
func (c *InvocationClient) Query() *InvocationQuery {
	return &InvocationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvocation},
		inters: c.Interceptors(),
	}
}

// Get returns a Invocation entity by its id.
func (c *InvocationClient) Get(ctx context.Context, id string) (*Invocation, error) {
	return c.Query().Where(invocation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InvocationClient) GetX(ctx context.Context, id string) *Invocation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTurn queries the turn edge of a Invocation.
func (c *InvocationClient) QueryTurn(_m *Invocation) *TurnQuery {
	query := (&TurnClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invocation.Table, invocation.FieldID, id),
			sqlgraph.To(turn.Table, turn.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invocation.TurnTable, invocation.TurnColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InvocationClient) Hooks() []Hook {
	return c.hooks.Invocation
}

// Interceptors returns the client interceptors.
func (c *InvocationClient) Interceptors() []Interceptor {
	return c.inters.Invocation
}

func (c *InvocationClient) mutate(ctx context.Context, m *InvocationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InvocationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InvocationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InvocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InvocationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Invocation mutation op: %q", m.Op())
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id string) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id string) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id string) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id string) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTasks queries the tasks edge of a Session.
func (c *SessionClient) QueryTasks(_m *Session) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.TasksTable, session.TasksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCheckpoints queries the checkpoints edge of a Session.
func (c *SessionClient) QueryCheckpoints(_m *Session) *CheckpointQuery {
	query := (&CheckpointClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(checkpoint.Table, checkpoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.CheckpointsTable, session.CheckpointsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Session.
func (c *SessionClient) QueryEvents(_m *Session) *EventQuery {
	query := (&EventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.EventsTable, session.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Session mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id string) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id string) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id string) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id string) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a Task.
func (c *TaskClient) QuerySession(_m *Task) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, task.SessionTable, task.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTurns queries the turns edge of a Task.
func (c *TaskClient) QueryTurns(_m *Task) *TurnQuery {
	query := (&TurnClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(turn.Table, turn.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.TurnsTable, task.TurnsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCandidates queries the candidates edge of a Task.
func (c *TaskClient) QueryCandidates(_m *Task) *CandidateQuery {
	query := (&CandidateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(candidate.Table, candidate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.CandidatesTable, task.CandidatesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBases queries the bases edge of a Task.
func (c *TaskClient) QueryBases(_m *Task) *TaskBaseQuery {
	query := (&TaskBaseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(taskbase.Table, taskbase.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.BasesTable, task.BasesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCheckpoints queries the checkpoints edge of a Task.
func (c *TaskClient) QueryCheckpoints(_m *Task) *CheckpointQuery {
	query := (&CheckpointClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(checkpoint.Table, checkpoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.CheckpointsTable, task.CheckpointsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Task.
func (c *TaskClient) QueryEvents(_m *Task) *EventQuery {
	query := (&EventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.EventsTable, task.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// TaskBaseClient is a client for the TaskBase schema.
type TaskBaseClient struct {
	config
}

// NewTaskBaseClient returns a client for the TaskBase from the given config.
func NewTaskBaseClient(c config) *TaskBaseClient {
	return &TaskBaseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `taskbase.Hooks(f(g(h())))`.
func (c *TaskBaseClient) Use(hooks ...Hook) {
	c.hooks.TaskBase = append(c.hooks.TaskBase, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `taskbase.Intercept(f(g(h())))`.
func (c *TaskBaseClient) Intercept(interceptors ...Interceptor) {
	c.inters.TaskBase = append(c.inters.TaskBase, interceptors...)
}

// Create returns a builder for creating a TaskBase entity.
func (c *TaskBaseClient) Create() *TaskBaseCreate {
	mutation := newTaskBaseMutation(c.config, OpCreate)
	return &TaskBaseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TaskBase entities.
func (c *TaskBaseClient) CreateBulk(builders ...*TaskBaseCreate) *TaskBaseCreateBulk {
	return &TaskBaseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskBaseClient) MapCreateBulk(slice any, setFunc func(*TaskBaseCreate, int)) *TaskBaseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskBaseCreateBulk{err: fmt.Errorf("calling to TaskBaseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskBaseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskBaseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TaskBase.
func (c *TaskBaseClient) Update() *TaskBaseUpdate {
	mutation := newTaskBaseMutation(c.config, OpUpdate)
	return &TaskBaseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskBaseClient) UpdateOne(_m *TaskBase) *TaskBaseUpdateOne {
	mutation := newTaskBaseMutation(c.config, OpUpdateOne, withTaskBase(_m))
	return &TaskBaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskBaseClient) UpdateOneID(id string) *TaskBaseUpdateOne {
	mutation := newTaskBaseMutation(c.config, OpUpdateOne, withTaskBaseID(id))
	return &TaskBaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TaskBase.
func (c *TaskBaseClient) Delete() *TaskBaseDelete {
	mutation := newTaskBaseMutation(c.config, OpDelete)
	return &TaskBaseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskBaseClient) DeleteOne(_m *TaskBase) *TaskBaseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskBaseClient) DeleteOneID(id string) *TaskBaseDeleteOne {
	builder := c.Delete().Where(taskbase.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskBaseDeleteOne{builder}
}

// Query returns a query builder for TaskBase.
func (c *TaskBaseClient) Query() *TaskBaseQuery {
	return &TaskBaseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTaskBase},
		inters: c.Interceptors(),
	}
}

// Get returns a TaskBase entity by its id.
func (c *TaskBaseClient) Get(ctx context.Context, id string) (*TaskBase, error) {
	return c.Query().Where(taskbase.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskBaseClient) GetX(ctx context.Context, id string) *TaskBase {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a TaskBase.
func (c *TaskBaseClient) QueryTask(_m *TaskBase) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taskbase.Table, taskbase.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskbase.TaskTable, taskbase.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskBaseClient) Hooks() []Hook {
	return c.hooks.TaskBase
}

// Interceptors returns the client interceptors.
func (c *TaskBaseClient) Interceptors() []Interceptor {
	return c.inters.TaskBase
}

func (c *TaskBaseClient) mutate(ctx context.Context, m *TaskBaseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskBaseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskBaseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskBaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskBaseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TaskBase mutation op: %q", m.Op())
	}
}

// TurnClient is a client for the Turn schema.
type TurnClient struct {
	config
}

// NewTurnClient returns a client for the Turn from the given config.
func NewTurnClient(c config) *TurnClient {
	return &TurnClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `turn.Hooks(f(g(h())))`.
func (c *TurnClient) Use(hooks ...Hook) {
	c.hooks.Turn = append(c.hooks.Turn, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `turn.Intercept(f(g(h())))`.
func (c *TurnClient) Intercept(interceptors ...Interceptor) {
	c.inters.Turn = append(c.inters.Turn, interceptors...)
}

// Create returns a builder for creating a Turn entity.
func (c *TurnClient) Create() *TurnCreate {
	mutation := newTurnMutation(c.config, OpCreate)
	return &TurnCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Turn entities.
func (c *TurnClient) CreateBulk(builders ...*TurnCreate) *TurnCreateBulk {
	return &TurnCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TurnClient) MapCreateBulk(slice any, setFunc func(*TurnCreate, int)) *TurnCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TurnCreateBulk{err: fmt.Errorf("calling to TurnClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TurnCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TurnCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Turn.
func (c *TurnClient) Update() *TurnUpdate {
	mutation := newTurnMutation(c.config, OpUpdate)
	return &TurnUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TurnClient) UpdateOne(_m *Turn) *TurnUpdateOne {
	mutation := newTurnMutation(c.config, OpUpdateOne, withTurn(_m))
	return &TurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TurnClient) UpdateOneID(id string) *TurnUpdateOne {
	mutation := newTurnMutation(c.config, OpUpdateOne, withTurnID(id))
	return &TurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Turn.
func (c *TurnClient) Delete() *TurnDelete {
	mutation := newTurnMutation(c.config, OpDelete)
	return &TurnDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TurnClient) DeleteOne(_m *Turn) *TurnDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TurnClient) DeleteOneID(id string) *TurnDeleteOne {
	builder := c.Delete().Where(turn.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TurnDeleteOne{builder}
}

// Query returns a query builder for Turn.
func (c *TurnClient) Query() *TurnQuery {
	return &TurnQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTurn},
		inters: c.Interceptors(),
	}
}

// Get returns a Turn entity by its id.
func (c *TurnClient) Get(ctx context.Context, id string) (*Turn, error) {
	return c.Query().Where(turn.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TurnClient) GetX(ctx context.Context, id string) *Turn {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a Turn.
func (c *TurnClient) QueryTask(_m *Turn) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(turn.Table, turn.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, turn.TaskTable, turn.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInvocations queries the invocations edge of a Turn.
func (c *TurnClient) QueryInvocations(_m *Turn) *InvocationQuery {
	query := (&InvocationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(turn.Table, turn.FieldID, id),
			sqlgraph.To(invocation.Table, invocation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, turn.InvocationsTable, turn.InvocationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TurnClient) Hooks() []Hook {
	return c.hooks.Turn
}

// Interceptors returns the client interceptors.
func (c *TurnClient) Interceptors() []Interceptor {
	return c.inters.Turn
}

func (c *TurnClient) mutate(ctx context.Context, m *TurnMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TurnCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TurnUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TurnDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Turn mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Candidate, Checkpoint, Event, Invocation, Session, Task, TaskBase,
		Turn []ent.Hook
	}
	inters struct {
		Candidate, Checkpoint, Event, Invocation, Session, Task, TaskBase,
		Turn []ent.Interceptor
	}
)
