// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/invocation"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
	"github.com/Covalane/turnyard/internal/store/ent/turn"
)

// InvocationUpdate is the builder for updating Invocation entities.
type InvocationUpdate struct {
	config
	hooks    []Hook
	mutation *InvocationMutation
}

// Where appends a list predicates to the InvocationUpdate builder.
func (_u *InvocationUpdate) Where(ps ...predicate.Invocation) *InvocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTurnID sets the "turn_id" field.
func (_u *InvocationUpdate) SetTurnID(v string) *InvocationUpdate {
	_u.mutation.SetTurnID(v)
	return _u
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableTurnID(v *string) *InvocationUpdate {
	if v != nil {
		_u.SetTurnID(*v)
	}
	return _u
}

// SetRuntime sets the "runtime" field.
func (_u *InvocationUpdate) SetRuntime(v string) *InvocationUpdate {
	_u.mutation.SetRuntime(v)
	return _u
}

// SetNillableRuntime sets the "runtime" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableRuntime(v *string) *InvocationUpdate {
	if v != nil {
		_u.SetRuntime(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *InvocationUpdate) SetModel(v string) *InvocationUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableModel(v *string) *InvocationUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSandboxBackend sets the "sandbox_backend" field.
func (_u *InvocationUpdate) SetSandboxBackend(v string) *InvocationUpdate {
	_u.mutation.SetSandboxBackend(v)
	return _u
}

// SetNillableSandboxBackend sets the "sandbox_backend" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableSandboxBackend(v *string) *InvocationUpdate {
	if v != nil {
		_u.SetSandboxBackend(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvocationUpdate) SetStatus(v string) *InvocationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableStatus(v *string) *InvocationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExitCode sets the "exit_code" field.
func (_u *InvocationUpdate) SetExitCode(v int) *InvocationUpdate {
	_u.mutation.ResetExitCode()
	_u.mutation.SetExitCode(v)
	return _u
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableExitCode(v *int) *InvocationUpdate {
	if v != nil {
		_u.SetExitCode(*v)
	}
	return _u
}

// AddExitCode adds value to the "exit_code" field.
func (_u *InvocationUpdate) AddExitCode(v int) *InvocationUpdate {
	_u.mutation.AddExitCode(v)
	return _u
}

// ClearExitCode clears the value of the "exit_code" field.
func (_u *InvocationUpdate) ClearExitCode() *InvocationUpdate {
	_u.mutation.ClearExitCode()
	return _u
}

// SetNativeID sets the "native_id" field.
func (_u *InvocationUpdate) SetNativeID(v string) *InvocationUpdate {
	_u.mutation.SetNativeID(v)
	return _u
}

// SetNillableNativeID sets the "native_id" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableNativeID(v *string) *InvocationUpdate {
	if v != nil {
		_u.SetNativeID(*v)
	}
	return _u
}

// ClearNativeID clears the value of the "native_id" field.
func (_u *InvocationUpdate) ClearNativeID() *InvocationUpdate {
	_u.mutation.ClearNativeID()
	return _u
}

// SetLogPath sets the "log_path" field.
func (_u *InvocationUpdate) SetLogPath(v string) *InvocationUpdate {
	_u.mutation.SetLogPath(v)
	return _u
}

// SetNillableLogPath sets the "log_path" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableLogPath(v *string) *InvocationUpdate {
	if v != nil {
		_u.SetLogPath(*v)
	}
	return _u
}

// ClearLogPath clears the value of the "log_path" field.
func (_u *InvocationUpdate) ClearLogPath() *InvocationUpdate {
	_u.mutation.ClearLogPath()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *InvocationUpdate) SetStartedAt(v float64) *InvocationUpdate {
	_u.mutation.ResetStartedAt()
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableStartedAt(v *float64) *InvocationUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// AddStartedAt adds value to the "started_at" field.
func (_u *InvocationUpdate) AddStartedAt(v float64) *InvocationUpdate {
	_u.mutation.AddStartedAt(v)
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *InvocationUpdate) SetEndedAt(v float64) *InvocationUpdate {
	_u.mutation.ResetEndedAt()
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *InvocationUpdate) SetNillableEndedAt(v *float64) *InvocationUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// AddEndedAt adds value to the "ended_at" field.
func (_u *InvocationUpdate) AddEndedAt(v float64) *InvocationUpdate {
	_u.mutation.AddEndedAt(v)
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *InvocationUpdate) ClearEndedAt() *InvocationUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetTurn sets the "turn" edge to the Turn entity.
func (_u *InvocationUpdate) SetTurn(v *Turn) *InvocationUpdate {
	return _u.SetTurnID(v.ID)
}

// Mutation returns the InvocationMutation object of the builder.
func (_u *InvocationUpdate) Mutation() *InvocationMutation {
	return _u.mutation
}

// ClearTurn clears the "turn" edge to the Turn entity.
func (_u *InvocationUpdate) ClearTurn() *InvocationUpdate {
	_u.mutation.ClearTurn()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvocationUpdate) check() error {
	if _u.mutation.TurnCleared() && len(_u.mutation.TurnIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invocation.turn"`)
	}
	return nil
}

func (_u *InvocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invocation.Table, invocation.Columns, sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Runtime(); ok {
		_spec.SetField(invocation.FieldRuntime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(invocation.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SandboxBackend(); ok {
		_spec.SetField(invocation.FieldSandboxBackend, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invocation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExitCode(); ok {
		_spec.SetField(invocation.FieldExitCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitCode(); ok {
		_spec.AddField(invocation.FieldExitCode, field.TypeInt, value)
	}
	if _u.mutation.ExitCodeCleared() {
		_spec.ClearField(invocation.FieldExitCode, field.TypeInt)
	}
	if value, ok := _u.mutation.NativeID(); ok {
		_spec.SetField(invocation.FieldNativeID, field.TypeString, value)
	}
	if _u.mutation.NativeIDCleared() {
		_spec.ClearField(invocation.FieldNativeID, field.TypeString)
	}
	if value, ok := _u.mutation.LogPath(); ok {
		_spec.SetField(invocation.FieldLogPath, field.TypeString, value)
	}
	if _u.mutation.LogPathCleared() {
		_spec.ClearField(invocation.FieldLogPath, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(invocation.FieldStartedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStartedAt(); ok {
		_spec.AddField(invocation.FieldStartedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(invocation.FieldEndedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndedAt(); ok {
		_spec.AddField(invocation.FieldEndedAt, field.TypeFloat64, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(invocation.FieldEndedAt, field.TypeFloat64)
	}
	if _u.mutation.TurnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invocation.TurnTable,
			Columns: []string{invocation.TurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invocation.TurnTable,
			Columns: []string{invocation.TurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvocationUpdateOne is the builder for updating a single Invocation entity.
type InvocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvocationMutation
}

// SetTurnID sets the "turn_id" field.
func (_u *InvocationUpdateOne) SetTurnID(v string) *InvocationUpdateOne {
	_u.mutation.SetTurnID(v)
	return _u
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableTurnID(v *string) *InvocationUpdateOne {
	if v != nil {
		_u.SetTurnID(*v)
	}
	return _u
}

// SetRuntime sets the "runtime" field.
func (_u *InvocationUpdateOne) SetRuntime(v string) *InvocationUpdateOne {
	_u.mutation.SetRuntime(v)
	return _u
}

// SetNillableRuntime sets the "runtime" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableRuntime(v *string) *InvocationUpdateOne {
	if v != nil {
		_u.SetRuntime(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *InvocationUpdateOne) SetModel(v string) *InvocationUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableModel(v *string) *InvocationUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSandboxBackend sets the "sandbox_backend" field.
func (_u *InvocationUpdateOne) SetSandboxBackend(v string) *InvocationUpdateOne {
	_u.mutation.SetSandboxBackend(v)
	return _u
}

// SetNillableSandboxBackend sets the "sandbox_backend" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableSandboxBackend(v *string) *InvocationUpdateOne {
	if v != nil {
		_u.SetSandboxBackend(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvocationUpdateOne) SetStatus(v string) *InvocationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableStatus(v *string) *InvocationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExitCode sets the "exit_code" field.
func (_u *InvocationUpdateOne) SetExitCode(v int) *InvocationUpdateOne {
	_u.mutation.ResetExitCode()
	_u.mutation.SetExitCode(v)
	return _u
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableExitCode(v *int) *InvocationUpdateOne {
	if v != nil {
		_u.SetExitCode(*v)
	}
	return _u
}

// AddExitCode adds value to the "exit_code" field.
func (_u *InvocationUpdateOne) AddExitCode(v int) *InvocationUpdateOne {
	_u.mutation.AddExitCode(v)
	return _u
}

// ClearExitCode clears the value of the "exit_code" field.
func (_u *InvocationUpdateOne) ClearExitCode() *InvocationUpdateOne {
	_u.mutation.ClearExitCode()
	return _u
}

// SetNativeID sets the "native_id" field.
func (_u *InvocationUpdateOne) SetNativeID(v string) *InvocationUpdateOne {
	_u.mutation.SetNativeID(v)
	return _u
}

// SetNillableNativeID sets the "native_id" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableNativeID(v *string) *InvocationUpdateOne {
	if v != nil {
		_u.SetNativeID(*v)
	}
	return _u
}

// ClearNativeID clears the value of the "native_id" field.
func (_u *InvocationUpdateOne) ClearNativeID() *InvocationUpdateOne {
	_u.mutation.ClearNativeID()
	return _u
}

// SetLogPath sets the "log_path" field.
func (_u *InvocationUpdateOne) SetLogPath(v string) *InvocationUpdateOne {
	_u.mutation.SetLogPath(v)
	return _u
}

// SetNillableLogPath sets the "log_path" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableLogPath(v *string) *InvocationUpdateOne {
	if v != nil {
		_u.SetLogPath(*v)
	}
	return _u
}

// ClearLogPath clears the value of the "log_path" field.
func (_u *InvocationUpdateOne) ClearLogPath() *InvocationUpdateOne {
	_u.mutation.ClearLogPath()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *InvocationUpdateOne) SetStartedAt(v float64) *InvocationUpdateOne {
	_u.mutation.ResetStartedAt()
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableStartedAt(v *float64) *InvocationUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// AddStartedAt adds value to the "started_at" field.
func (_u *InvocationUpdateOne) AddStartedAt(v float64) *InvocationUpdateOne {
	_u.mutation.AddStartedAt(v)
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *InvocationUpdateOne) SetEndedAt(v float64) *InvocationUpdateOne {
	_u.mutation.ResetEndedAt()
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *InvocationUpdateOne) SetNillableEndedAt(v *float64) *InvocationUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// AddEndedAt adds value to the "ended_at" field.
func (_u *InvocationUpdateOne) AddEndedAt(v float64) *InvocationUpdateOne {
	_u.mutation.AddEndedAt(v)
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *InvocationUpdateOne) ClearEndedAt() *InvocationUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetTurn sets the "turn" edge to the Turn entity.
func (_u *InvocationUpdateOne) SetTurn(v *Turn) *InvocationUpdateOne {
	return _u.SetTurnID(v.ID)
}

// Mutation returns the InvocationMutation object of the builder.
func (_u *InvocationUpdateOne) Mutation() *InvocationMutation {
	return _u.mutation
}

// ClearTurn clears the "turn" edge to the Turn entity.
func (_u *InvocationUpdateOne) ClearTurn() *InvocationUpdateOne {
	_u.mutation.ClearTurn()
	return _u
}

// Where appends a list predicates to the InvocationUpdate builder.
func (_u *InvocationUpdateOne) Where(ps ...predicate.Invocation) *InvocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvocationUpdateOne) Select(field string, fields ...string) *InvocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invocation entity.
func (_u *InvocationUpdateOne) Save(ctx context.Context) (*Invocation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvocationUpdateOne) SaveX(ctx context.Context) *Invocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvocationUpdateOne) check() error {
	if _u.mutation.TurnCleared() && len(_u.mutation.TurnIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invocation.turn"`)
	}
	return nil
}

func (_u *InvocationUpdateOne) sqlSave(ctx context.Context) (_node *Invocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invocation.Table, invocation.Columns, sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invocation.FieldID)
		for _, f := range fields {
			if !invocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Runtime(); ok {
		_spec.SetField(invocation.FieldRuntime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(invocation.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SandboxBackend(); ok {
		_spec.SetField(invocation.FieldSandboxBackend, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invocation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExitCode(); ok {
		_spec.SetField(invocation.FieldExitCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitCode(); ok {
		_spec.AddField(invocation.FieldExitCode, field.TypeInt, value)
	}
	if _u.mutation.ExitCodeCleared() {
		_spec.ClearField(invocation.FieldExitCode, field.TypeInt)
	}
	if value, ok := _u.mutation.NativeID(); ok {
		_spec.SetField(invocation.FieldNativeID, field.TypeString, value)
	}
	if _u.mutation.NativeIDCleared() {
		_spec.ClearField(invocation.FieldNativeID, field.TypeString)
	}
	if value, ok := _u.mutation.LogPath(); ok {
		_spec.SetField(invocation.FieldLogPath, field.TypeString, value)
	}
	if _u.mutation.LogPathCleared() {
		_spec.ClearField(invocation.FieldLogPath, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(invocation.FieldStartedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStartedAt(); ok {
		_spec.AddField(invocation.FieldStartedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(invocation.FieldEndedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndedAt(); ok {
		_spec.AddField(invocation.FieldEndedAt, field.TypeFloat64, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(invocation.FieldEndedAt, field.TypeFloat64)
	}
	if _u.mutation.TurnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invocation.TurnTable,
			Columns: []string{invocation.TurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invocation.TurnTable,
			Columns: []string{invocation.TurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
