// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Covalane/turnyard/internal/store/ent/candidate"
	"github.com/Covalane/turnyard/internal/store/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	candidateFields := schema.Candidate{}.Fields()
	_ = candidateFields
	// candidateDescDeliverables is the schema descriptor for deliverables field.
	candidateDescDeliverables := candidateFields[5].Descriptor()
	// candidate.DefaultDeliverables holds the default value on creation for the deliverables field.
	candidate.DefaultDeliverables = candidateDescDeliverables.Default.(string)
}
