// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Covalane/turnyard/internal/store/ent/session"
)

// Session is the model entity for the Session schema.
type Session struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Spec holds the value of the "spec" field.
	Spec string `json:"spec,omitempty"`
	// Environment holds the value of the "environment" field.
	Environment string `json:"environment,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// CreationDigest holds the value of the "creation_digest" field.
	CreationDigest *string `json:"creation_digest,omitempty"`
	// EnvironmentDigest holds the value of the "environment_digest" field.
	EnvironmentDigest string `json:"environment_digest,omitempty"`
	// Workspace holds the value of the "workspace" field.
	Workspace string `json:"workspace,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// NativeID holds the value of the "native_id" field.
	NativeID *string `json:"native_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt float64 `json:"created_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *float64 `json:"completed_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt *float64 `json:"cancelled_at,omitempty"`
	// CancelReason holds the value of the "cancel_reason" field.
	CancelReason *string `json:"cancel_reason,omitempty"`
	// ParentSessionID holds the value of the "parent_session_id" field.
	ParentSessionID *string `json:"parent_session_id,omitempty"`
	// ParentTaskID holds the value of the "parent_task_id" field.
	ParentTaskID *string `json:"parent_task_id,omitempty"`
	// ParentInvocationID holds the value of the "parent_invocation_id" field.
	ParentInvocationID *string `json:"parent_invocation_id,omitempty"`
	// DelegateAgentID holds the value of the "delegate_agent_id" field.
	DelegateAgentID *string `json:"delegate_agent_id,omitempty"`
	// DelegationRequestDigest holds the value of the "delegation_request_digest" field.
	DelegationRequestDigest *string `json:"delegation_request_digest,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SessionQuery when eager-loading is set.
	Edges        SessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SessionEdges holds the relations/edges for other nodes in the graph.
type SessionEdges struct {
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// Checkpoints holds the value of the checkpoints edge.
	Checkpoints []*Checkpoint `json:"checkpoints,omitempty"`
	// Events holds the value of the events edge.
	Events []*Event `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e SessionEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[0] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// CheckpointsOrErr returns the Checkpoints value or an error if the edge
// was not loaded in eager-loading.
func (e SessionEdges) CheckpointsOrErr() ([]*Checkpoint, error) {
	if e.loadedTypes[1] {
		return e.Checkpoints, nil
	}
	return nil, &NotLoadedError{edge: "checkpoints"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e SessionEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[2] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Session) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case session.FieldCreatedAt, session.FieldCompletedAt, session.FieldCancelledAt:
			values[i] = new(sql.NullFloat64)
		case session.FieldID, session.FieldSpec, session.FieldEnvironment, session.FieldIdempotencyKey, session.FieldCreationDigest, session.FieldEnvironmentDigest, session.FieldWorkspace, session.FieldStatus, session.FieldNativeID, session.FieldCancelReason, session.FieldParentSessionID, session.FieldParentTaskID, session.FieldParentInvocationID, session.FieldDelegateAgentID, session.FieldDelegationRequestDigest:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Session fields.
func (_m *Session) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case session.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case session.FieldSpec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spec", values[i])
			} else if value.Valid {
				_m.Spec = value.String
			}
		case session.FieldEnvironment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value.Valid {
				_m.Environment = value.String
			}
		case session.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case session.FieldCreationDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creation_digest", values[i])
			} else if value.Valid {
				_m.CreationDigest = new(string)
				*_m.CreationDigest = value.String
			}
		case session.FieldEnvironmentDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_digest", values[i])
			} else if value.Valid {
				_m.EnvironmentDigest = value.String
			}
		case session.FieldWorkspace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace", values[i])
			} else if value.Valid {
				_m.Workspace = value.String
			}
		case session.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case session.FieldNativeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field native_id", values[i])
			} else if value.Valid {
				_m.NativeID = new(string)
				*_m.NativeID = value.String
			}
		case session.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Float64
			}
		case session.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(float64)
				*_m.CompletedAt = value.Float64
			}
		case session.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(float64)
				*_m.CancelledAt = value.Float64
			}
		case session.FieldCancelReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_reason", values[i])
			} else if value.Valid {
				_m.CancelReason = new(string)
				*_m.CancelReason = value.String
			}
		case session.FieldParentSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_session_id", values[i])
			} else if value.Valid {
				_m.ParentSessionID = new(string)
				*_m.ParentSessionID = value.String
			}
		case session.FieldParentTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_task_id", values[i])
			} else if value.Valid {
				_m.ParentTaskID = new(string)
				*_m.ParentTaskID = value.String
			}
		case session.FieldParentInvocationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_invocation_id", values[i])
			} else if value.Valid {
				_m.ParentInvocationID = new(string)
				*_m.ParentInvocationID = value.String
			}
		case session.FieldDelegateAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delegate_agent_id", values[i])
			} else if value.Valid {
				_m.DelegateAgentID = new(string)
				*_m.DelegateAgentID = value.String
			}
		case session.FieldDelegationRequestDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delegation_request_digest", values[i])
			} else if value.Valid {
				_m.DelegationRequestDigest = new(string)
				*_m.DelegationRequestDigest = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Session.
// This includes values selected through modifiers, order, etc.
func (_m *Session) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTasks queries the "tasks" edge of the Session entity.
func (_m *Session) QueryTasks() *TaskQuery {
	return NewSessionClient(_m.config).QueryTasks(_m)
}

// QueryCheckpoints queries the "checkpoints" edge of the Session entity.
func (_m *Session) QueryCheckpoints() *CheckpointQuery {
	return NewSessionClient(_m.config).QueryCheckpoints(_m)
}

// QueryEvents queries the "events" edge of the Session entity.
func (_m *Session) QueryEvents() *EventQuery {
	return NewSessionClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Session.
// Note that you need to call Session.Unwrap() before calling this method if this Session
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Session) Update() *SessionUpdateOne {
	return NewSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Session entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Session) Unwrap() *Session {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Session is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Session) String() string {
	var builder strings.Builder
	builder.WriteString("Session(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("spec=")
	builder.WriteString(_m.Spec)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(_m.Environment)
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreationDigest; v != nil {
		builder.WriteString("creation_digest=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("environment_digest=")
	builder.WriteString(_m.EnvironmentDigest)
	builder.WriteString(", ")
	builder.WriteString("workspace=")
	builder.WriteString(_m.Workspace)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.NativeID; v != nil {
		builder.WriteString("native_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CancelReason; v != nil {
		builder.WriteString("cancel_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentSessionID; v != nil {
		builder.WriteString("parent_session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentTaskID; v != nil {
		builder.WriteString("parent_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentInvocationID; v != nil {
		builder.WriteString("parent_invocation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DelegateAgentID; v != nil {
		builder.WriteString("delegate_agent_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DelegationRequestDigest; v != nil {
		builder.WriteString("delegation_request_digest=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Sessions is a parsable slice of Session.
type Sessions []*Session
