// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/checkpoint"
	"github.com/Covalane/turnyard/internal/store/ent/event"
	"github.com/Covalane/turnyard/internal/store/ent/session"
	"github.com/Covalane/turnyard/internal/store/ent/task"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetSpec sets the "spec" field.
func (_c *SessionCreate) SetSpec(v string) *SessionCreate {
	_c.mutation.SetSpec(v)
	return _c
}

// SetEnvironment sets the "environment" field.
func (_c *SessionCreate) SetEnvironment(v string) *SessionCreate {
	_c.mutation.SetEnvironment(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *SessionCreate) SetIdempotencyKey(v string) *SessionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *SessionCreate) SetNillableIdempotencyKey(v *string) *SessionCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetCreationDigest sets the "creation_digest" field.
func (_c *SessionCreate) SetCreationDigest(v string) *SessionCreate {
	_c.mutation.SetCreationDigest(v)
	return _c
}

// SetNillableCreationDigest sets the "creation_digest" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCreationDigest(v *string) *SessionCreate {
	if v != nil {
		_c.SetCreationDigest(*v)
	}
	return _c
}

// SetEnvironmentDigest sets the "environment_digest" field.
func (_c *SessionCreate) SetEnvironmentDigest(v string) *SessionCreate {
	_c.mutation.SetEnvironmentDigest(v)
	return _c
}

// SetWorkspace sets the "workspace" field.
func (_c *SessionCreate) SetWorkspace(v string) *SessionCreate {
	_c.mutation.SetWorkspace(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SessionCreate) SetStatus(v string) *SessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNativeID sets the "native_id" field.
func (_c *SessionCreate) SetNativeID(v string) *SessionCreate {
	_c.mutation.SetNativeID(v)
	return _c
}

// SetNillableNativeID sets the "native_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableNativeID(v *string) *SessionCreate {
	if v != nil {
		_c.SetNativeID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SessionCreate) SetCreatedAt(v float64) *SessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *SessionCreate) SetCompletedAt(v float64) *SessionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCompletedAt(v *float64) *SessionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *SessionCreate) SetCancelledAt(v float64) *SessionCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCancelledAt(v *float64) *SessionCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetCancelReason sets the "cancel_reason" field.
func (_c *SessionCreate) SetCancelReason(v string) *SessionCreate {
	_c.mutation.SetCancelReason(v)
	return _c
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCancelReason(v *string) *SessionCreate {
	if v != nil {
		_c.SetCancelReason(*v)
	}
	return _c
}

// SetParentSessionID sets the "parent_session_id" field.
func (_c *SessionCreate) SetParentSessionID(v string) *SessionCreate {
	_c.mutation.SetParentSessionID(v)
	return _c
}

// SetNillableParentSessionID sets the "parent_session_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableParentSessionID(v *string) *SessionCreate {
	if v != nil {
		_c.SetParentSessionID(*v)
	}
	return _c
}

// SetParentTaskID sets the "parent_task_id" field.
func (_c *SessionCreate) SetParentTaskID(v string) *SessionCreate {
	_c.mutation.SetParentTaskID(v)
	return _c
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableParentTaskID(v *string) *SessionCreate {
	if v != nil {
		_c.SetParentTaskID(*v)
	}
	return _c
}

// SetParentInvocationID sets the "parent_invocation_id" field.
func (_c *SessionCreate) SetParentInvocationID(v string) *SessionCreate {
	_c.mutation.SetParentInvocationID(v)
	return _c
}

// SetNillableParentInvocationID sets the "parent_invocation_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableParentInvocationID(v *string) *SessionCreate {
	if v != nil {
		_c.SetParentInvocationID(*v)
	}
	return _c
}

// SetDelegateAgentID sets the "delegate_agent_id" field.
func (_c *SessionCreate) SetDelegateAgentID(v string) *SessionCreate {
	_c.mutation.SetDelegateAgentID(v)
	return _c
}

// SetNillableDelegateAgentID sets the "delegate_agent_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableDelegateAgentID(v *string) *SessionCreate {
	if v != nil {
		_c.SetDelegateAgentID(*v)
	}
	return _c
}

// SetDelegationRequestDigest sets the "delegation_request_digest" field.
func (_c *SessionCreate) SetDelegationRequestDigest(v string) *SessionCreate {
	_c.mutation.SetDelegationRequestDigest(v)
	return _c
}

// SetNillableDelegationRequestDigest sets the "delegation_request_digest" field if the given value is not nil.
func (_c *SessionCreate) SetNillableDelegationRequestDigest(v *string) *SessionCreate {
	if v != nil {
		_c.SetDelegationRequestDigest(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionCreate) SetID(v string) *SessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *SessionCreate) AddTaskIDs(ids ...string) *SessionCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *SessionCreate) AddTasks(v ...*Task) *SessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// AddCheckpointIDs adds the "checkpoints" edge to the Checkpoint entity by IDs.
func (_c *SessionCreate) AddCheckpointIDs(ids ...string) *SessionCreate {
	_c.mutation.AddCheckpointIDs(ids...)
	return _c
}

// AddCheckpoints adds the "checkpoints" edges to the Checkpoint entity.
func (_c *SessionCreate) AddCheckpoints(v ...*Checkpoint) *SessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCheckpointIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *SessionCreate) AddEventIDs(ids ...int64) *SessionCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *SessionCreate) AddEvents(v ...*Event) *SessionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.Spec(); !ok {
		return &ValidationError{Name: "spec", err: errors.New(`ent: missing required field "Session.spec"`)}
	}
	if _, ok := _c.mutation.Environment(); !ok {
		return &ValidationError{Name: "environment", err: errors.New(`ent: missing required field "Session.environment"`)}
	}
	if _, ok := _c.mutation.EnvironmentDigest(); !ok {
		return &ValidationError{Name: "environment_digest", err: errors.New(`ent: missing required field "Session.environment_digest"`)}
	}
	if _, ok := _c.mutation.Workspace(); !ok {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required field "Session.workspace"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Session.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Session.created_at"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Session.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Spec(); ok {
		_spec.SetField(session.FieldSpec, field.TypeString, value)
		_node.Spec = value
	}
	if value, ok := _c.mutation.Environment(); ok {
		_spec.SetField(session.FieldEnvironment, field.TypeString, value)
		_node.Environment = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(session.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.CreationDigest(); ok {
		_spec.SetField(session.FieldCreationDigest, field.TypeString, value)
		_node.CreationDigest = &value
	}
	if value, ok := _c.mutation.EnvironmentDigest(); ok {
		_spec.SetField(session.FieldEnvironmentDigest, field.TypeString, value)
		_node.EnvironmentDigest = value
	}
	if value, ok := _c.mutation.Workspace(); ok {
		_spec.SetField(session.FieldWorkspace, field.TypeString, value)
		_node.Workspace = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(session.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NativeID(); ok {
		_spec.SetField(session.FieldNativeID, field.TypeString, value)
		_node.NativeID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeFloat64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(session.FieldCompletedAt, field.TypeFloat64, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(session.FieldCancelledAt, field.TypeFloat64, value)
		_node.CancelledAt = &value
	}
	if value, ok := _c.mutation.CancelReason(); ok {
		_spec.SetField(session.FieldCancelReason, field.TypeString, value)
		_node.CancelReason = &value
	}
	if value, ok := _c.mutation.ParentSessionID(); ok {
		_spec.SetField(session.FieldParentSessionID, field.TypeString, value)
		_node.ParentSessionID = &value
	}
	if value, ok := _c.mutation.ParentTaskID(); ok {
		_spec.SetField(session.FieldParentTaskID, field.TypeString, value)
		_node.ParentTaskID = &value
	}
	if value, ok := _c.mutation.ParentInvocationID(); ok {
		_spec.SetField(session.FieldParentInvocationID, field.TypeString, value)
		_node.ParentInvocationID = &value
	}
	if value, ok := _c.mutation.DelegateAgentID(); ok {
		_spec.SetField(session.FieldDelegateAgentID, field.TypeString, value)
		_node.DelegateAgentID = &value
	}
	if value, ok := _c.mutation.DelegationRequestDigest(); ok {
		_spec.SetField(session.FieldDelegationRequestDigest, field.TypeString, value)
		_node.DelegationRequestDigest = &value
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.TasksTable,
			Columns: []string{session.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CheckpointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.CheckpointsTable,
			Columns: []string{session.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.EventsTable,
			Columns: []string{session.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
