// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/candidate"
	"github.com/Covalane/turnyard/internal/store/ent/checkpoint"
	"github.com/Covalane/turnyard/internal/store/ent/event"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
	"github.com/Covalane/turnyard/internal/store/ent/session"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/taskbase"
	"github.com/Covalane/turnyard/internal/store/ent/turn"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *TaskUpdate) SetSessionID(v string) *TaskUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSessionID(v *string) *TaskUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *TaskUpdate) SetSequence(v int) *TaskUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSequence(v *int) *TaskUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *TaskUpdate) AddSequence(v int) *TaskUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *TaskUpdate) SetIdempotencyKey(v string) *TaskUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableIdempotencyKey(v *string) *TaskUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetSpec sets the "spec" field.
func (_u *TaskUpdate) SetSpec(v string) *TaskUpdate {
	_u.mutation.SetSpec(v)
	return _u
}

// SetNillableSpec sets the "spec" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSpec(v *string) *TaskUpdate {
	if v != nil {
		_u.SetSpec(*v)
	}
	return _u
}

// SetSpecDigest sets the "spec_digest" field.
func (_u *TaskUpdate) SetSpecDigest(v string) *TaskUpdate {
	_u.mutation.SetSpecDigest(v)
	return _u
}

// SetNillableSpecDigest sets the "spec_digest" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSpecDigest(v *string) *TaskUpdate {
	if v != nil {
		_u.SetSpecDigest(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v string) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *string) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCandidateID sets the "candidate_id" field.
func (_u *TaskUpdate) SetCandidateID(v string) *TaskUpdate {
	_u.mutation.SetCandidateID(v)
	return _u
}

// SetNillableCandidateID sets the "candidate_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCandidateID(v *string) *TaskUpdate {
	if v != nil {
		_u.SetCandidateID(*v)
	}
	return _u
}

// ClearCandidateID clears the value of the "candidate_id" field.
func (_u *TaskUpdate) ClearCandidateID() *TaskUpdate {
	_u.mutation.ClearCandidateID()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *TaskUpdate) SetErrorCode(v string) *TaskUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableErrorCode(v *string) *TaskUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *TaskUpdate) ClearErrorCode() *TaskUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaskUpdate) SetCreatedAt(v float64) *TaskUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCreatedAt(v *float64) *TaskUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *TaskUpdate) AddCreatedAt(v float64) *TaskUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *TaskUpdate) SetSession(v *Session) *TaskUpdate {
	return _u.SetSessionID(v.ID)
}

// AddTurnIDs adds the "turns" edge to the Turn entity by IDs.
func (_u *TaskUpdate) AddTurnIDs(ids ...string) *TaskUpdate {
	_u.mutation.AddTurnIDs(ids...)
	return _u
}

// AddTurns adds the "turns" edges to the Turn entity.
func (_u *TaskUpdate) AddTurns(v ...*Turn) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTurnIDs(ids...)
}

// AddCandidateIDs adds the "candidates" edge to the Candidate entity by IDs.
func (_u *TaskUpdate) AddCandidateIDs(ids ...string) *TaskUpdate {
	_u.mutation.AddCandidateIDs(ids...)
	return _u
}

// AddCandidates adds the "candidates" edges to the Candidate entity.
func (_u *TaskUpdate) AddCandidates(v ...*Candidate) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCandidateIDs(ids...)
}

// AddBasisIDs adds the "bases" edge to the TaskBase entity by IDs.
func (_u *TaskUpdate) AddBasisIDs(ids ...string) *TaskUpdate {
	_u.mutation.AddBasisIDs(ids...)
	return _u
}

// AddBases adds the "bases" edges to the TaskBase entity.
func (_u *TaskUpdate) AddBases(v ...*TaskBase) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBasisIDs(ids...)
}

// AddCheckpointIDs adds the "checkpoints" edge to the Checkpoint entity by IDs.
func (_u *TaskUpdate) AddCheckpointIDs(ids ...string) *TaskUpdate {
	_u.mutation.AddCheckpointIDs(ids...)
	return _u
}

// AddCheckpoints adds the "checkpoints" edges to the Checkpoint entity.
func (_u *TaskUpdate) AddCheckpoints(v ...*Checkpoint) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckpointIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *TaskUpdate) AddEventIDs(ids ...int64) *TaskUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *TaskUpdate) AddEvents(v ...*Event) *TaskUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *TaskUpdate) ClearSession() *TaskUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearTurns clears all "turns" edges to the Turn entity.
func (_u *TaskUpdate) ClearTurns() *TaskUpdate {
	_u.mutation.ClearTurns()
	return _u
}

// RemoveTurnIDs removes the "turns" edge to Turn entities by IDs.
func (_u *TaskUpdate) RemoveTurnIDs(ids ...string) *TaskUpdate {
	_u.mutation.RemoveTurnIDs(ids...)
	return _u
}

// RemoveTurns removes "turns" edges to Turn entities.
func (_u *TaskUpdate) RemoveTurns(v ...*Turn) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTurnIDs(ids...)
}

// ClearCandidates clears all "candidates" edges to the Candidate entity.
func (_u *TaskUpdate) ClearCandidates() *TaskUpdate {
	_u.mutation.ClearCandidates()
	return _u
}

// RemoveCandidateIDs removes the "candidates" edge to Candidate entities by IDs.
func (_u *TaskUpdate) RemoveCandidateIDs(ids ...string) *TaskUpdate {
	_u.mutation.RemoveCandidateIDs(ids...)
	return _u
}

// RemoveCandidates removes "candidates" edges to Candidate entities.
func (_u *TaskUpdate) RemoveCandidates(v ...*Candidate) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCandidateIDs(ids...)
}

// ClearBases clears all "bases" edges to the TaskBase entity.
func (_u *TaskUpdate) ClearBases() *TaskUpdate {
	_u.mutation.ClearBases()
	return _u
}

// RemoveBasisIDs removes the "bases" edge to TaskBase entities by IDs.
func (_u *TaskUpdate) RemoveBasisIDs(ids ...string) *TaskUpdate {
	_u.mutation.RemoveBasisIDs(ids...)
	return _u
}

// RemoveBases removes "bases" edges to TaskBase entities.
func (_u *TaskUpdate) RemoveBases(v ...*TaskBase) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBasisIDs(ids...)
}

// ClearCheckpoints clears all "checkpoints" edges to the Checkpoint entity.
func (_u *TaskUpdate) ClearCheckpoints() *TaskUpdate {
	_u.mutation.ClearCheckpoints()
	return _u
}

// RemoveCheckpointIDs removes the "checkpoints" edge to Checkpoint entities by IDs.
func (_u *TaskUpdate) RemoveCheckpointIDs(ids ...string) *TaskUpdate {
	_u.mutation.RemoveCheckpointIDs(ids...)
	return _u
}

// RemoveCheckpoints removes "checkpoints" edges to Checkpoint entities.
func (_u *TaskUpdate) RemoveCheckpoints(v ...*Checkpoint) *TaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckpointIDs(ids...)
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *TaskUpdate) ClearEvents() *TaskUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *TaskUpdate) RemoveEventIDs(ids ...int64) *TaskUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *TaskUpdate) RemoveEvents(v ...*Event) *TaskUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.session"`)
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(task.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(task.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(task.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Spec(); ok {
		_spec.SetField(task.FieldSpec, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecDigest(); ok {
		_spec.SetField(task.FieldSpecDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CandidateID(); ok {
		_spec.SetField(task.FieldCandidateID, field.TypeString, value)
	}
	if _u.mutation.CandidateIDCleared() {
		_spec.ClearField(task.FieldCandidateID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(task.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(task.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(task.FieldCreatedAt, field.TypeFloat64, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SessionTable,
			Columns: []string{task.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SessionTable,
			Columns: []string{task.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TurnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TurnsTable,
			Columns: []string{task.TurnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTurnsIDs(); len(nodes) > 0 && !_u.mutation.TurnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TurnsTable,
			Columns: []string{task.TurnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TurnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TurnsTable,
			Columns: []string{task.TurnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CandidatesTable,
			Columns: []string{task.CandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCandidatesIDs(); len(nodes) > 0 && !_u.mutation.CandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CandidatesTable,
			Columns: []string{task.CandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CandidatesTable,
			Columns: []string{task.CandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.BasesTable,
			Columns: []string{task.BasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBasesIDs(); len(nodes) > 0 && !_u.mutation.BasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.BasesTable,
			Columns: []string{task.BasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.BasesTable,
			Columns: []string{task.BasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CheckpointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CheckpointsTable,
			Columns: []string{task.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCheckpointsIDs(); len(nodes) > 0 && !_u.mutation.CheckpointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CheckpointsTable,
			Columns: []string{task.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckpointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CheckpointsTable,
			Columns: []string{task.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetSessionID sets the "session_id" field.
func (_u *TaskUpdateOne) SetSessionID(v string) *TaskUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSessionID(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *TaskUpdateOne) SetSequence(v int) *TaskUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSequence(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *TaskUpdateOne) AddSequence(v int) *TaskUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *TaskUpdateOne) SetIdempotencyKey(v string) *TaskUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableIdempotencyKey(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetSpec sets the "spec" field.
func (_u *TaskUpdateOne) SetSpec(v string) *TaskUpdateOne {
	_u.mutation.SetSpec(v)
	return _u
}

// SetNillableSpec sets the "spec" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSpec(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetSpec(*v)
	}
	return _u
}

// SetSpecDigest sets the "spec_digest" field.
func (_u *TaskUpdateOne) SetSpecDigest(v string) *TaskUpdateOne {
	_u.mutation.SetSpecDigest(v)
	return _u
}

// SetNillableSpecDigest sets the "spec_digest" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSpecDigest(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetSpecDigest(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v string) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCandidateID sets the "candidate_id" field.
func (_u *TaskUpdateOne) SetCandidateID(v string) *TaskUpdateOne {
	_u.mutation.SetCandidateID(v)
	return _u
}

// SetNillableCandidateID sets the "candidate_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCandidateID(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetCandidateID(*v)
	}
	return _u
}

// ClearCandidateID clears the value of the "candidate_id" field.
func (_u *TaskUpdateOne) ClearCandidateID() *TaskUpdateOne {
	_u.mutation.ClearCandidateID()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *TaskUpdateOne) SetErrorCode(v string) *TaskUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableErrorCode(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *TaskUpdateOne) ClearErrorCode() *TaskUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaskUpdateOne) SetCreatedAt(v float64) *TaskUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCreatedAt(v *float64) *TaskUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *TaskUpdateOne) AddCreatedAt(v float64) *TaskUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *TaskUpdateOne) SetSession(v *Session) *TaskUpdateOne {
	return _u.SetSessionID(v.ID)
}

// AddTurnIDs adds the "turns" edge to the Turn entity by IDs.
func (_u *TaskUpdateOne) AddTurnIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.AddTurnIDs(ids...)
	return _u
}

// AddTurns adds the "turns" edges to the Turn entity.
func (_u *TaskUpdateOne) AddTurns(v ...*Turn) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTurnIDs(ids...)
}

// AddCandidateIDs adds the "candidates" edge to the Candidate entity by IDs.
func (_u *TaskUpdateOne) AddCandidateIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.AddCandidateIDs(ids...)
	return _u
}

// AddCandidates adds the "candidates" edges to the Candidate entity.
func (_u *TaskUpdateOne) AddCandidates(v ...*Candidate) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCandidateIDs(ids...)
}

// AddBasisIDs adds the "bases" edge to the TaskBase entity by IDs.
func (_u *TaskUpdateOne) AddBasisIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.AddBasisIDs(ids...)
	return _u
}

// AddBases adds the "bases" edges to the TaskBase entity.
func (_u *TaskUpdateOne) AddBases(v ...*TaskBase) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBasisIDs(ids...)
}

// AddCheckpointIDs adds the "checkpoints" edge to the Checkpoint entity by IDs.
func (_u *TaskUpdateOne) AddCheckpointIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.AddCheckpointIDs(ids...)
	return _u
}

// AddCheckpoints adds the "checkpoints" edges to the Checkpoint entity.
func (_u *TaskUpdateOne) AddCheckpoints(v ...*Checkpoint) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckpointIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *TaskUpdateOne) AddEventIDs(ids ...int64) *TaskUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *TaskUpdateOne) AddEvents(v ...*Event) *TaskUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *TaskUpdateOne) ClearSession() *TaskUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearTurns clears all "turns" edges to the Turn entity.
func (_u *TaskUpdateOne) ClearTurns() *TaskUpdateOne {
	_u.mutation.ClearTurns()
	return _u
}

// RemoveTurnIDs removes the "turns" edge to Turn entities by IDs.
func (_u *TaskUpdateOne) RemoveTurnIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.RemoveTurnIDs(ids...)
	return _u
}

// RemoveTurns removes "turns" edges to Turn entities.
func (_u *TaskUpdateOne) RemoveTurns(v ...*Turn) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTurnIDs(ids...)
}

// ClearCandidates clears all "candidates" edges to the Candidate entity.
func (_u *TaskUpdateOne) ClearCandidates() *TaskUpdateOne {
	_u.mutation.ClearCandidates()
	return _u
}

// RemoveCandidateIDs removes the "candidates" edge to Candidate entities by IDs.
func (_u *TaskUpdateOne) RemoveCandidateIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.RemoveCandidateIDs(ids...)
	return _u
}

// RemoveCandidates removes "candidates" edges to Candidate entities.
func (_u *TaskUpdateOne) RemoveCandidates(v ...*Candidate) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCandidateIDs(ids...)
}

// ClearBases clears all "bases" edges to the TaskBase entity.
func (_u *TaskUpdateOne) ClearBases() *TaskUpdateOne {
	_u.mutation.ClearBases()
	return _u
}

// RemoveBasisIDs removes the "bases" edge to TaskBase entities by IDs.
func (_u *TaskUpdateOne) RemoveBasisIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.RemoveBasisIDs(ids...)
	return _u
}

// RemoveBases removes "bases" edges to TaskBase entities.
func (_u *TaskUpdateOne) RemoveBases(v ...*TaskBase) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBasisIDs(ids...)
}

// ClearCheckpoints clears all "checkpoints" edges to the Checkpoint entity.
func (_u *TaskUpdateOne) ClearCheckpoints() *TaskUpdateOne {
	_u.mutation.ClearCheckpoints()
	return _u
}

// RemoveCheckpointIDs removes the "checkpoints" edge to Checkpoint entities by IDs.
func (_u *TaskUpdateOne) RemoveCheckpointIDs(ids ...string) *TaskUpdateOne {
	_u.mutation.RemoveCheckpointIDs(ids...)
	return _u
}

// RemoveCheckpoints removes "checkpoints" edges to Checkpoint entities.
func (_u *TaskUpdateOne) RemoveCheckpoints(v ...*Checkpoint) *TaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckpointIDs(ids...)
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *TaskUpdateOne) ClearEvents() *TaskUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *TaskUpdateOne) RemoveEventIDs(ids ...int64) *TaskUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *TaskUpdateOne) RemoveEvents(v ...*Event) *TaskUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.session"`)
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(task.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(task.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(task.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Spec(); ok {
		_spec.SetField(task.FieldSpec, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecDigest(); ok {
		_spec.SetField(task.FieldSpecDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CandidateID(); ok {
		_spec.SetField(task.FieldCandidateID, field.TypeString, value)
	}
	if _u.mutation.CandidateIDCleared() {
		_spec.ClearField(task.FieldCandidateID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(task.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(task.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(task.FieldCreatedAt, field.TypeFloat64, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SessionTable,
			Columns: []string{task.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SessionTable,
			Columns: []string{task.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TurnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TurnsTable,
			Columns: []string{task.TurnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTurnsIDs(); len(nodes) > 0 && !_u.mutation.TurnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TurnsTable,
			Columns: []string{task.TurnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TurnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TurnsTable,
			Columns: []string{task.TurnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CandidatesTable,
			Columns: []string{task.CandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCandidatesIDs(); len(nodes) > 0 && !_u.mutation.CandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CandidatesTable,
			Columns: []string{task.CandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CandidatesTable,
			Columns: []string{task.CandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.BasesTable,
			Columns: []string{task.BasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBasesIDs(); len(nodes) > 0 && !_u.mutation.BasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.BasesTable,
			Columns: []string{task.BasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.BasesTable,
			Columns: []string{task.BasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CheckpointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CheckpointsTable,
			Columns: []string{task.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCheckpointsIDs(); len(nodes) > 0 && !_u.mutation.CheckpointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CheckpointsTable,
			Columns: []string{task.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckpointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CheckpointsTable,
			Columns: []string{task.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
