// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/taskbase"
)

// TaskBaseUpdate is the builder for updating TaskBase entities.
type TaskBaseUpdate struct {
	config
	hooks    []Hook
	mutation *TaskBaseMutation
}

// Where appends a list predicates to the TaskBaseUpdate builder.
func (_u *TaskBaseUpdate) Where(ps ...predicate.TaskBase) *TaskBaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TaskBaseUpdate) SetTaskID(v string) *TaskBaseUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskBaseUpdate) SetNillableTaskID(v *string) *TaskBaseUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetRepoID sets the "repo_id" field.
func (_u *TaskBaseUpdate) SetRepoID(v string) *TaskBaseUpdate {
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *TaskBaseUpdate) SetNillableRepoID(v *string) *TaskBaseUpdate {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// SetBaseCommit sets the "base_commit" field.
func (_u *TaskBaseUpdate) SetBaseCommit(v string) *TaskBaseUpdate {
	_u.mutation.SetBaseCommit(v)
	return _u
}

// SetNillableBaseCommit sets the "base_commit" field if the given value is not nil.
func (_u *TaskBaseUpdate) SetNillableBaseCommit(v *string) *TaskBaseUpdate {
	if v != nil {
		_u.SetBaseCommit(*v)
	}
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskBaseUpdate) SetTask(v *Task) *TaskBaseUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the TaskBaseMutation object of the builder.
func (_u *TaskBaseUpdate) Mutation() *TaskBaseMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskBaseUpdate) ClearTask() *TaskBaseUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskBaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskBaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskBaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskBaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskBaseUpdate) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskBase.task"`)
	}
	return nil
}

func (_u *TaskBaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskbase.Table, taskbase.Columns, sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(taskbase.FieldRepoID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseCommit(); ok {
		_spec.SetField(taskbase.FieldBaseCommit, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskbase.TaskTable,
			Columns: []string{taskbase.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskbase.TaskTable,
			Columns: []string{taskbase.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskbase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskBaseUpdateOne is the builder for updating a single TaskBase entity.
type TaskBaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskBaseMutation
}

// SetTaskID sets the "task_id" field.
func (_u *TaskBaseUpdateOne) SetTaskID(v string) *TaskBaseUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskBaseUpdateOne) SetNillableTaskID(v *string) *TaskBaseUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetRepoID sets the "repo_id" field.
func (_u *TaskBaseUpdateOne) SetRepoID(v string) *TaskBaseUpdateOne {
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *TaskBaseUpdateOne) SetNillableRepoID(v *string) *TaskBaseUpdateOne {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// SetBaseCommit sets the "base_commit" field.
func (_u *TaskBaseUpdateOne) SetBaseCommit(v string) *TaskBaseUpdateOne {
	_u.mutation.SetBaseCommit(v)
	return _u
}

// SetNillableBaseCommit sets the "base_commit" field if the given value is not nil.
func (_u *TaskBaseUpdateOne) SetNillableBaseCommit(v *string) *TaskBaseUpdateOne {
	if v != nil {
		_u.SetBaseCommit(*v)
	}
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskBaseUpdateOne) SetTask(v *Task) *TaskBaseUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the TaskBaseMutation object of the builder.
func (_u *TaskBaseUpdateOne) Mutation() *TaskBaseMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskBaseUpdateOne) ClearTask() *TaskBaseUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the TaskBaseUpdate builder.
func (_u *TaskBaseUpdateOne) Where(ps ...predicate.TaskBase) *TaskBaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskBaseUpdateOne) Select(field string, fields ...string) *TaskBaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskBase entity.
func (_u *TaskBaseUpdateOne) Save(ctx context.Context) (*TaskBase, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskBaseUpdateOne) SaveX(ctx context.Context) *TaskBase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskBaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskBaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskBaseUpdateOne) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskBase.task"`)
	}
	return nil
}

func (_u *TaskBaseUpdateOne) sqlSave(ctx context.Context) (_node *TaskBase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskbase.Table, taskbase.Columns, sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskBase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskbase.FieldID)
		for _, f := range fields {
			if !taskbase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskbase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(taskbase.FieldRepoID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseCommit(); ok {
		_spec.SetField(taskbase.FieldBaseCommit, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskbase.TaskTable,
			Columns: []string{taskbase.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskbase.TaskTable,
			Columns: []string{taskbase.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskBase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskbase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
