// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/candidate"
	"github.com/Covalane/turnyard/internal/store/ent/checkpoint"
	"github.com/Covalane/turnyard/internal/store/ent/event"
	"github.com/Covalane/turnyard/internal/store/ent/session"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/taskbase"
	"github.com/Covalane/turnyard/internal/store/ent/turn"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *TaskCreate) SetSessionID(v string) *TaskCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetSequence sets the "sequence" field.
func (_c *TaskCreate) SetSequence(v int) *TaskCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *TaskCreate) SetIdempotencyKey(v string) *TaskCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetSpec sets the "spec" field.
func (_c *TaskCreate) SetSpec(v string) *TaskCreate {
	_c.mutation.SetSpec(v)
	return _c
}

// SetSpecDigest sets the "spec_digest" field.
func (_c *TaskCreate) SetSpecDigest(v string) *TaskCreate {
	_c.mutation.SetSpecDigest(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TaskCreate) SetStatus(v string) *TaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCandidateID sets the "candidate_id" field.
func (_c *TaskCreate) SetCandidateID(v string) *TaskCreate {
	_c.mutation.SetCandidateID(v)
	return _c
}

// SetNillableCandidateID sets the "candidate_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCandidateID(v *string) *TaskCreate {
	if v != nil {
		_c.SetCandidateID(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *TaskCreate) SetErrorCode(v string) *TaskCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *TaskCreate) SetNillableErrorCode(v *string) *TaskCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskCreate) SetCreatedAt(v float64) *TaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TaskCreate) SetID(v string) *TaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *TaskCreate) SetSession(v *Session) *TaskCreate {
	return _c.SetSessionID(v.ID)
}

// AddTurnIDs adds the "turns" edge to the Turn entity by IDs.
func (_c *TaskCreate) AddTurnIDs(ids ...string) *TaskCreate {
	_c.mutation.AddTurnIDs(ids...)
	return _c
}

// AddTurns adds the "turns" edges to the Turn entity.
func (_c *TaskCreate) AddTurns(v ...*Turn) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTurnIDs(ids...)
}

// AddCandidateIDs adds the "candidates" edge to the Candidate entity by IDs.
func (_c *TaskCreate) AddCandidateIDs(ids ...string) *TaskCreate {
	_c.mutation.AddCandidateIDs(ids...)
	return _c
}

// AddCandidates adds the "candidates" edges to the Candidate entity.
func (_c *TaskCreate) AddCandidates(v ...*Candidate) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCandidateIDs(ids...)
}

// AddBasisIDs adds the "bases" edge to the TaskBase entity by IDs.
func (_c *TaskCreate) AddBasisIDs(ids ...string) *TaskCreate {
	_c.mutation.AddBasisIDs(ids...)
	return _c
}

// AddBases adds the "bases" edges to the TaskBase entity.
func (_c *TaskCreate) AddBases(v ...*TaskBase) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBasisIDs(ids...)
}

// AddCheckpointIDs adds the "checkpoints" edge to the Checkpoint entity by IDs.
func (_c *TaskCreate) AddCheckpointIDs(ids ...string) *TaskCreate {
	_c.mutation.AddCheckpointIDs(ids...)
	return _c
}

// AddCheckpoints adds the "checkpoints" edges to the Checkpoint entity.
func (_c *TaskCreate) AddCheckpoints(v ...*Checkpoint) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCheckpointIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *TaskCreate) AddEventIDs(ids ...int64) *TaskCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *TaskCreate) AddEvents(v ...*Event) *TaskCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Task.session_id"`)}
	}
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "Task.sequence"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "Task.idempotency_key"`)}
	}
	if _, ok := _c.mutation.Spec(); !ok {
		return &ValidationError{Name: "spec", err: errors.New(`ent: missing required field "Task.spec"`)}
	}
	if _, ok := _c.mutation.SpecDigest(); !ok {
		return &ValidationError{Name: "spec_digest", err: errors.New(`ent: missing required field "Task.spec_digest"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Task.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Task.session"`)}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Task.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(task.FieldSequence, field.TypeInt, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(task.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Spec(); ok {
		_spec.SetField(task.FieldSpec, field.TypeString, value)
		_node.Spec = value
	}
	if value, ok := _c.mutation.SpecDigest(); ok {
		_spec.SetField(task.FieldSpecDigest, field.TypeString, value)
		_node.SpecDigest = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CandidateID(); ok {
		_spec.SetField(task.FieldCandidateID, field.TypeString, value)
		_node.CandidateID = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(task.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeFloat64, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SessionTable,
			Columns: []string{task.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TurnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TurnsTable,
			Columns: []string{task.TurnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CandidatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CandidatesTable,
			Columns: []string{task.CandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.BasesTable,
			Columns: []string{task.BasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CheckpointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CheckpointsTable,
			Columns: []string{task.CheckpointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
