// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Covalane/turnyard/internal/store/ent/session"
	"github.com/Covalane/turnyard/internal/store/ent/task"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// Sequence holds the value of the "sequence" field.
	Sequence int `json:"sequence,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// Spec holds the value of the "spec" field.
	Spec string `json:"spec,omitempty"`
	// SpecDigest holds the value of the "spec_digest" field.
	SpecDigest string `json:"spec_digest,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CandidateID holds the value of the "candidate_id" field.
	CandidateID *string `json:"candidate_id,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt float64 `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges        TaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// Turns holds the value of the turns edge.
	Turns []*Turn `json:"turns,omitempty"`
	// Candidates holds the value of the candidates edge.
	Candidates []*Candidate `json:"candidates,omitempty"`
	// Bases holds the value of the bases edge.
	Bases []*TaskBase `json:"bases,omitempty"`
	// Checkpoints holds the value of the checkpoints edge.
	Checkpoints []*Checkpoint `json:"checkpoints,omitempty"`
	// Events holds the value of the events edge.
	Events []*Event `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// TurnsOrErr returns the Turns value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) TurnsOrErr() ([]*Turn, error) {
	if e.loadedTypes[1] {
		return e.Turns, nil
	}
	return nil, &NotLoadedError{edge: "turns"}
}

// CandidatesOrErr returns the Candidates value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) CandidatesOrErr() ([]*Candidate, error) {
	if e.loadedTypes[2] {
		return e.Candidates, nil
	}
	return nil, &NotLoadedError{edge: "candidates"}
}

// BasesOrErr returns the Bases value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) BasesOrErr() ([]*TaskBase, error) {
	if e.loadedTypes[3] {
		return e.Bases, nil
	}
	return nil, &NotLoadedError{edge: "bases"}
}

// CheckpointsOrErr returns the Checkpoints value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) CheckpointsOrErr() ([]*Checkpoint, error) {
	if e.loadedTypes[4] {
		return e.Checkpoints, nil
	}
	return nil, &NotLoadedError{edge: "checkpoints"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[5] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldCreatedAt:
			values[i] = new(sql.NullFloat64)
		case task.FieldSequence:
			values[i] = new(sql.NullInt64)
		case task.FieldID, task.FieldSessionID, task.FieldIdempotencyKey, task.FieldSpec, task.FieldSpecDigest, task.FieldStatus, task.FieldCandidateID, task.FieldErrorCode:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case task.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case task.FieldSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence", values[i])
			} else if value.Valid {
				_m.Sequence = int(value.Int64)
			}
		case task.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case task.FieldSpec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spec", values[i])
			} else if value.Valid {
				_m.Spec = value.String
			}
		case task.FieldSpecDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spec_digest", values[i])
			} else if value.Valid {
				_m.SpecDigest = value.String
			}
		case task.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case task.FieldCandidateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_id", values[i])
			} else if value.Valid {
				_m.CandidateID = new(string)
				*_m.CandidateID = value.String
			}
		case task.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the Task entity.
func (_m *Task) QuerySession() *SessionQuery {
	return NewTaskClient(_m.config).QuerySession(_m)
}

// QueryTurns queries the "turns" edge of the Task entity.
func (_m *Task) QueryTurns() *TurnQuery {
	return NewTaskClient(_m.config).QueryTurns(_m)
}

// QueryCandidates queries the "candidates" edge of the Task entity.
func (_m *Task) QueryCandidates() *CandidateQuery {
	return NewTaskClient(_m.config).QueryCandidates(_m)
}

// QueryBases queries the "bases" edge of the Task entity.
func (_m *Task) QueryBases() *TaskBaseQuery {
	return NewTaskClient(_m.config).QueryBases(_m)
}

// QueryCheckpoints queries the "checkpoints" edge of the Task entity.
func (_m *Task) QueryCheckpoints() *CheckpointQuery {
	return NewTaskClient(_m.config).QueryCheckpoints(_m)
}

// QueryEvents queries the "events" edge of the Task entity.
func (_m *Task) QueryEvents() *EventQuery {
	return NewTaskClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sequence))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("spec=")
	builder.WriteString(_m.Spec)
	builder.WriteString(", ")
	builder.WriteString("spec_digest=")
	builder.WriteString(_m.SpecDigest)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.CandidateID; v != nil {
		builder.WriteString("candidate_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
