// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/taskbase"
)

// TaskBase is the model entity for the TaskBase schema.
type TaskBase struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// RepoID holds the value of the "repo_id" field.
	RepoID string `json:"repo_id,omitempty"`
	// BaseCommit holds the value of the "base_commit" field.
	BaseCommit string `json:"base_commit,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskBaseQuery when eager-loading is set.
	Edges        TaskBaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskBaseEdges holds the relations/edges for other nodes in the graph.
type TaskBaseEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskBaseEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskBase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskbase.FieldID, taskbase.FieldTaskID, taskbase.FieldRepoID, taskbase.FieldBaseCommit:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskBase fields.
func (_m *TaskBase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskbase.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case taskbase.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case taskbase.FieldRepoID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_id", values[i])
			} else if value.Valid {
				_m.RepoID = value.String
			}
		case taskbase.FieldBaseCommit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_commit", values[i])
			} else if value.Valid {
				_m.BaseCommit = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskBase.
// This includes values selected through modifiers, order, etc.
func (_m *TaskBase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskBase entity.
func (_m *TaskBase) QueryTask() *TaskQuery {
	return NewTaskBaseClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this TaskBase.
// Note that you need to call TaskBase.Unwrap() before calling this method if this TaskBase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskBase) Update() *TaskBaseUpdateOne {
	return NewTaskBaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskBase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskBase) Unwrap() *TaskBase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskBase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskBase) String() string {
	var builder strings.Builder
	builder.WriteString("TaskBase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("repo_id=")
	builder.WriteString(_m.RepoID)
	builder.WriteString(", ")
	builder.WriteString("base_commit=")
	builder.WriteString(_m.BaseCommit)
	builder.WriteByte(')')
	return builder.String()
}

// TaskBases is a parsable slice of TaskBase.
type TaskBases []*TaskBase
