// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/taskbase"
)

// TaskBaseCreate is the builder for creating a TaskBase entity.
type TaskBaseCreate struct {
	config
	mutation *TaskBaseMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *TaskBaseCreate) SetTaskID(v string) *TaskBaseCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetRepoID sets the "repo_id" field.
func (_c *TaskBaseCreate) SetRepoID(v string) *TaskBaseCreate {
	_c.mutation.SetRepoID(v)
	return _c
}

// SetBaseCommit sets the "base_commit" field.
func (_c *TaskBaseCreate) SetBaseCommit(v string) *TaskBaseCreate {
	_c.mutation.SetBaseCommit(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TaskBaseCreate) SetID(v string) *TaskBaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskBaseCreate) SetTask(v *Task) *TaskBaseCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the TaskBaseMutation object of the builder.
func (_c *TaskBaseCreate) Mutation() *TaskBaseMutation {
	return _c.mutation
}

// Save creates the TaskBase in the database.
func (_c *TaskBaseCreate) Save(ctx context.Context) (*TaskBase, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskBaseCreate) SaveX(ctx context.Context) *TaskBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskBaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskBaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskBaseCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskBase.task_id"`)}
	}
	if _, ok := _c.mutation.RepoID(); !ok {
		return &ValidationError{Name: "repo_id", err: errors.New(`ent: missing required field "TaskBase.repo_id"`)}
	}
	if _, ok := _c.mutation.BaseCommit(); !ok {
		return &ValidationError{Name: "base_commit", err: errors.New(`ent: missing required field "TaskBase.base_commit"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskBase.task"`)}
	}
	return nil
}

func (_c *TaskBaseCreate) sqlSave(ctx context.Context) (*TaskBase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TaskBase.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskBaseCreate) createSpec() (*TaskBase, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskBase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskbase.Table, sqlgraph.NewFieldSpec(taskbase.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RepoID(); ok {
		_spec.SetField(taskbase.FieldRepoID, field.TypeString, value)
		_node.RepoID = value
	}
	if value, ok := _c.mutation.BaseCommit(); ok {
		_spec.SetField(taskbase.FieldBaseCommit, field.TypeString, value)
		_node.BaseCommit = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskbase.TaskTable,
			Columns: []string{taskbase.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskBaseCreateBulk is the builder for creating many TaskBase entities in bulk.
type TaskBaseCreateBulk struct {
	config
	err      error
	builders []*TaskBaseCreate
}

// Save creates the TaskBase entities in the database.
func (_c *TaskBaseCreateBulk) Save(ctx context.Context) ([]*TaskBase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskBase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskBaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskBaseCreateBulk) SaveX(ctx context.Context) []*TaskBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskBaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskBaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
