// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/turn"
)

// Turn is the model entity for the Turn schema.
type Turn struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// Sequence holds the value of the "sequence" field.
	Sequence int `json:"sequence,omitempty"`
	// Input holds the value of the "input" field.
	Input string `json:"input,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// InvocationID holds the value of the "invocation_id" field.
	InvocationID *string `json:"invocation_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt float64 `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TurnQuery when eager-loading is set.
	Edges        TurnEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TurnEdges holds the relations/edges for other nodes in the graph.
type TurnEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// Invocations holds the value of the invocations edge.
	Invocations []*Invocation `json:"invocations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TurnEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// InvocationsOrErr returns the Invocations value or an error if the edge
// was not loaded in eager-loading.
func (e TurnEdges) InvocationsOrErr() ([]*Invocation, error) {
	if e.loadedTypes[1] {
		return e.Invocations, nil
	}
	return nil, &NotLoadedError{edge: "invocations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Turn) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case turn.FieldCreatedAt:
			values[i] = new(sql.NullFloat64)
		case turn.FieldSequence:
			values[i] = new(sql.NullInt64)
		case turn.FieldID, turn.FieldTaskID, turn.FieldInput, turn.FieldStatus, turn.FieldInvocationID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Turn fields.
func (_m *Turn) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case turn.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case turn.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case turn.FieldSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence", values[i])
			} else if value.Valid {
				_m.Sequence = int(value.Int64)
			}
		case turn.FieldInput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input", values[i])
			} else if value.Valid {
				_m.Input = value.String
			}
		case turn.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case turn.FieldInvocationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invocation_id", values[i])
			} else if value.Valid {
				_m.InvocationID = new(string)
				*_m.InvocationID = value.String
			}
		case turn.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Turn.
// This includes values selected through modifiers, order, etc.
func (_m *Turn) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Turn entity.
func (_m *Turn) QueryTask() *TaskQuery {
	return NewTurnClient(_m.config).QueryTask(_m)
}

// QueryInvocations queries the "invocations" edge of the Turn entity.
func (_m *Turn) QueryInvocations() *InvocationQuery {
	return NewTurnClient(_m.config).QueryInvocations(_m)
}

// Update returns a builder for updating this Turn.
// Note that you need to call Turn.Unwrap() before calling this method if this Turn
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Turn) Update() *TurnUpdateOne {
	return NewTurnClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Turn entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Turn) Unwrap() *Turn {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Turn is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Turn) String() string {
	var builder strings.Builder
	builder.WriteString("Turn(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sequence))
	builder.WriteString(", ")
	builder.WriteString("input=")
	builder.WriteString(_m.Input)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.InvocationID; v != nil {
		builder.WriteString("invocation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteByte(')')
	return builder.String()
}

// Turns is a parsable slice of Turn.
type Turns []*Turn
