// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/invocation"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/turn"
)

// TurnUpdate is the builder for updating Turn entities.
type TurnUpdate struct {
	config
	hooks    []Hook
	mutation *TurnMutation
}

// Where appends a list predicates to the TurnUpdate builder.
func (_u *TurnUpdate) Where(ps ...predicate.Turn) *TurnUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TurnUpdate) SetTaskID(v string) *TurnUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TurnUpdate) SetNillableTaskID(v *string) *TurnUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *TurnUpdate) SetSequence(v int) *TurnUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *TurnUpdate) SetNillableSequence(v *int) *TurnUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *TurnUpdate) AddSequence(v int) *TurnUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetInput sets the "input" field.
func (_u *TurnUpdate) SetInput(v string) *TurnUpdate {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *TurnUpdate) SetNillableInput(v *string) *TurnUpdate {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TurnUpdate) SetStatus(v string) *TurnUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TurnUpdate) SetNillableStatus(v *string) *TurnUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInvocationID sets the "invocation_id" field.
func (_u *TurnUpdate) SetInvocationID(v string) *TurnUpdate {
	_u.mutation.SetInvocationID(v)
	return _u
}

// SetNillableInvocationID sets the "invocation_id" field if the given value is not nil.
func (_u *TurnUpdate) SetNillableInvocationID(v *string) *TurnUpdate {
	if v != nil {
		_u.SetInvocationID(*v)
	}
	return _u
}

// ClearInvocationID clears the value of the "invocation_id" field.
func (_u *TurnUpdate) ClearInvocationID() *TurnUpdate {
	_u.mutation.ClearInvocationID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TurnUpdate) SetCreatedAt(v float64) *TurnUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TurnUpdate) SetNillableCreatedAt(v *float64) *TurnUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *TurnUpdate) AddCreatedAt(v float64) *TurnUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TurnUpdate) SetTask(v *Task) *TurnUpdate {
	return _u.SetTaskID(v.ID)
}

// AddInvocationIDs adds the "invocations" edge to the Invocation entity by IDs.
func (_u *TurnUpdate) AddInvocationIDs(ids ...string) *TurnUpdate {
	_u.mutation.AddInvocationIDs(ids...)
	return _u
}

// AddInvocations adds the "invocations" edges to the Invocation entity.
func (_u *TurnUpdate) AddInvocations(v ...*Invocation) *TurnUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvocationIDs(ids...)
}

// Mutation returns the TurnMutation object of the builder.
func (_u *TurnUpdate) Mutation() *TurnMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TurnUpdate) ClearTask() *TurnUpdate {
	_u.mutation.ClearTask()
	return _u
}

// ClearInvocations clears all "invocations" edges to the Invocation entity.
func (_u *TurnUpdate) ClearInvocations() *TurnUpdate {
	_u.mutation.ClearInvocations()
	return _u
}

// RemoveInvocationIDs removes the "invocations" edge to Invocation entities by IDs.
func (_u *TurnUpdate) RemoveInvocationIDs(ids ...string) *TurnUpdate {
	_u.mutation.RemoveInvocationIDs(ids...)
	return _u
}

// RemoveInvocations removes "invocations" edges to Invocation entities.
func (_u *TurnUpdate) RemoveInvocations(v ...*Invocation) *TurnUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvocationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TurnUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TurnUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TurnUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TurnUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TurnUpdate) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Turn.task"`)
	}
	return nil
}

func (_u *TurnUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(turn.Table, turn.Columns, sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(turn.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(turn.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(turn.FieldInput, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(turn.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvocationID(); ok {
		_spec.SetField(turn.FieldInvocationID, field.TypeString, value)
	}
	if _u.mutation.InvocationIDCleared() {
		_spec.ClearField(turn.FieldInvocationID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(turn.FieldCreatedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(turn.FieldCreatedAt, field.TypeFloat64, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   turn.TaskTable,
			Columns: []string{turn.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   turn.TaskTable,
			Columns: []string{turn.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   turn.InvocationsTable,
			Columns: []string{turn.InvocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvocationsIDs(); len(nodes) > 0 && !_u.mutation.InvocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   turn.InvocationsTable,
			Columns: []string{turn.InvocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   turn.InvocationsTable,
			Columns: []string{turn.InvocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{turn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TurnUpdateOne is the builder for updating a single Turn entity.
type TurnUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TurnMutation
}

// SetTaskID sets the "task_id" field.
func (_u *TurnUpdateOne) SetTaskID(v string) *TurnUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TurnUpdateOne) SetNillableTaskID(v *string) *TurnUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *TurnUpdateOne) SetSequence(v int) *TurnUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *TurnUpdateOne) SetNillableSequence(v *int) *TurnUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *TurnUpdateOne) AddSequence(v int) *TurnUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetInput sets the "input" field.
func (_u *TurnUpdateOne) SetInput(v string) *TurnUpdateOne {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *TurnUpdateOne) SetNillableInput(v *string) *TurnUpdateOne {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TurnUpdateOne) SetStatus(v string) *TurnUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TurnUpdateOne) SetNillableStatus(v *string) *TurnUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInvocationID sets the "invocation_id" field.
func (_u *TurnUpdateOne) SetInvocationID(v string) *TurnUpdateOne {
	_u.mutation.SetInvocationID(v)
	return _u
}

// SetNillableInvocationID sets the "invocation_id" field if the given value is not nil.
func (_u *TurnUpdateOne) SetNillableInvocationID(v *string) *TurnUpdateOne {
	if v != nil {
		_u.SetInvocationID(*v)
	}
	return _u
}

// ClearInvocationID clears the value of the "invocation_id" field.
func (_u *TurnUpdateOne) ClearInvocationID() *TurnUpdateOne {
	_u.mutation.ClearInvocationID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TurnUpdateOne) SetCreatedAt(v float64) *TurnUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TurnUpdateOne) SetNillableCreatedAt(v *float64) *TurnUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *TurnUpdateOne) AddCreatedAt(v float64) *TurnUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TurnUpdateOne) SetTask(v *Task) *TurnUpdateOne {
	return _u.SetTaskID(v.ID)
}

// AddInvocationIDs adds the "invocations" edge to the Invocation entity by IDs.
func (_u *TurnUpdateOne) AddInvocationIDs(ids ...string) *TurnUpdateOne {
	_u.mutation.AddInvocationIDs(ids...)
	return _u
}

// AddInvocations adds the "invocations" edges to the Invocation entity.
func (_u *TurnUpdateOne) AddInvocations(v ...*Invocation) *TurnUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvocationIDs(ids...)
}

// Mutation returns the TurnMutation object of the builder.
func (_u *TurnUpdateOne) Mutation() *TurnMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TurnUpdateOne) ClearTask() *TurnUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// ClearInvocations clears all "invocations" edges to the Invocation entity.
func (_u *TurnUpdateOne) ClearInvocations() *TurnUpdateOne {
	_u.mutation.ClearInvocations()
	return _u
}

// RemoveInvocationIDs removes the "invocations" edge to Invocation entities by IDs.
func (_u *TurnUpdateOne) RemoveInvocationIDs(ids ...string) *TurnUpdateOne {
	_u.mutation.RemoveInvocationIDs(ids...)
	return _u
}

// RemoveInvocations removes "invocations" edges to Invocation entities.
func (_u *TurnUpdateOne) RemoveInvocations(v ...*Invocation) *TurnUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvocationIDs(ids...)
}

// Where appends a list predicates to the TurnUpdate builder.
func (_u *TurnUpdateOne) Where(ps ...predicate.Turn) *TurnUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TurnUpdateOne) Select(field string, fields ...string) *TurnUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Turn entity.
func (_u *TurnUpdateOne) Save(ctx context.Context) (*Turn, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TurnUpdateOne) SaveX(ctx context.Context) *Turn {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TurnUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TurnUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TurnUpdateOne) check() error {
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Turn.task"`)
	}
	return nil
}

func (_u *TurnUpdateOne) sqlSave(ctx context.Context) (_node *Turn, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(turn.Table, turn.Columns, sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Turn.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, turn.FieldID)
		for _, f := range fields {
			if !turn.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != turn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(turn.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(turn.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(turn.FieldInput, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(turn.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvocationID(); ok {
		_spec.SetField(turn.FieldInvocationID, field.TypeString, value)
	}
	if _u.mutation.InvocationIDCleared() {
		_spec.ClearField(turn.FieldInvocationID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(turn.FieldCreatedAt, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(turn.FieldCreatedAt, field.TypeFloat64, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   turn.TaskTable,
			Columns: []string{turn.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   turn.TaskTable,
			Columns: []string{turn.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   turn.InvocationsTable,
			Columns: []string{turn.InvocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvocationsIDs(); len(nodes) > 0 && !_u.mutation.InvocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   turn.InvocationsTable,
			Columns: []string{turn.InvocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   turn.InvocationsTable,
			Columns: []string{turn.InvocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Turn{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{turn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
