// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Covalane/turnyard/internal/store/ent/invocation"
	"github.com/Covalane/turnyard/internal/store/ent/task"
	"github.com/Covalane/turnyard/internal/store/ent/turn"
)

// TurnCreate is the builder for creating a Turn entity.
type TurnCreate struct {
	config
	mutation *TurnMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *TurnCreate) SetTaskID(v string) *TurnCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetSequence sets the "sequence" field.
func (_c *TurnCreate) SetSequence(v int) *TurnCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetInput sets the "input" field.
func (_c *TurnCreate) SetInput(v string) *TurnCreate {
	_c.mutation.SetInput(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TurnCreate) SetStatus(v string) *TurnCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetInvocationID sets the "invocation_id" field.
func (_c *TurnCreate) SetInvocationID(v string) *TurnCreate {
	_c.mutation.SetInvocationID(v)
	return _c
}

// SetNillableInvocationID sets the "invocation_id" field if the given value is not nil.
func (_c *TurnCreate) SetNillableInvocationID(v *string) *TurnCreate {
	if v != nil {
		_c.SetInvocationID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TurnCreate) SetCreatedAt(v float64) *TurnCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TurnCreate) SetID(v string) *TurnCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TurnCreate) SetTask(v *Task) *TurnCreate {
	return _c.SetTaskID(v.ID)
}

// AddInvocationIDs adds the "invocations" edge to the Invocation entity by IDs.
func (_c *TurnCreate) AddInvocationIDs(ids ...string) *TurnCreate {
	_c.mutation.AddInvocationIDs(ids...)
	return _c
}

// AddInvocations adds the "invocations" edges to the Invocation entity.
func (_c *TurnCreate) AddInvocations(v ...*Invocation) *TurnCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInvocationIDs(ids...)
}

// Mutation returns the TurnMutation object of the builder.
func (_c *TurnCreate) Mutation() *TurnMutation {
	return _c.mutation
}

// Save creates the Turn in the database.
func (_c *TurnCreate) Save(ctx context.Context) (*Turn, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TurnCreate) SaveX(ctx context.Context) *Turn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TurnCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TurnCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TurnCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "Turn.task_id"`)}
	}
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "Turn.sequence"`)}
	}
	if _, ok := _c.mutation.Input(); !ok {
		return &ValidationError{Name: "input", err: errors.New(`ent: missing required field "Turn.input"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Turn.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Turn.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "Turn.task"`)}
	}
	return nil
}

func (_c *TurnCreate) sqlSave(ctx context.Context) (*Turn, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Turn.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TurnCreate) createSpec() (*Turn, *sqlgraph.CreateSpec) {
	var (
		_node = &Turn{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(turn.Table, sqlgraph.NewFieldSpec(turn.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(turn.FieldSequence, field.TypeInt, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.Input(); ok {
		_spec.SetField(turn.FieldInput, field.TypeString, value)
		_node.Input = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(turn.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InvocationID(); ok {
		_spec.SetField(turn.FieldInvocationID, field.TypeString, value)
		_node.InvocationID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(turn.FieldCreatedAt, field.TypeFloat64, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   turn.TaskTable,
			Columns: []string{turn.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   turn.InvocationsTable,
			Columns: []string{turn.InvocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invocation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TurnCreateBulk is the builder for creating many Turn entities in bulk.
type TurnCreateBulk struct {
	config
	err      error
	builders []*TurnCreate
}

// Save creates the Turn entities in the database.
func (_c *TurnCreateBulk) Save(ctx context.Context) ([]*Turn, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Turn, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TurnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TurnCreateBulk) SaveX(ctx context.Context) []*Turn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TurnCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TurnCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
