// Code generated by ent, DO NOT EDIT.

package invocation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldID, id))
}

// TurnID applies equality check predicate on the "turn_id" field. It's identical to TurnIDEQ.
func TurnID(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldTurnID, v))
}

// Runtime applies equality check predicate on the "runtime" field. It's identical to RuntimeEQ.
func Runtime(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldRuntime, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldModel, v))
}

// SandboxBackend applies equality check predicate on the "sandbox_backend" field. It's identical to SandboxBackendEQ.
func SandboxBackend(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldSandboxBackend, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldStatus, v))
}

// ExitCode applies equality check predicate on the "exit_code" field. It's identical to ExitCodeEQ.
func ExitCode(v int) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldExitCode, v))
}

// NativeID applies equality check predicate on the "native_id" field. It's identical to NativeIDEQ.
func NativeID(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldNativeID, v))
}

// LogPath applies equality check predicate on the "log_path" field. It's identical to LogPathEQ.
func LogPath(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldLogPath, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldEndedAt, v))
}

// TurnIDEQ applies the EQ predicate on the "turn_id" field.
func TurnIDEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldTurnID, v))
}

// TurnIDNEQ applies the NEQ predicate on the "turn_id" field.
func TurnIDNEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldTurnID, v))
}

// TurnIDIn applies the In predicate on the "turn_id" field.
func TurnIDIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldTurnID, vs...))
}

// TurnIDNotIn applies the NotIn predicate on the "turn_id" field.
func TurnIDNotIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldTurnID, vs...))
}

// TurnIDGT applies the GT predicate on the "turn_id" field.
func TurnIDGT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldTurnID, v))
}

// TurnIDGTE applies the GTE predicate on the "turn_id" field.
func TurnIDGTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldTurnID, v))
}

// TurnIDLT applies the LT predicate on the "turn_id" field.
func TurnIDLT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldTurnID, v))
}

// TurnIDLTE applies the LTE predicate on the "turn_id" field.
func TurnIDLTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldTurnID, v))
}

// TurnIDContains applies the Contains predicate on the "turn_id" field.
func TurnIDContains(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContains(FieldTurnID, v))
}

// TurnIDHasPrefix applies the HasPrefix predicate on the "turn_id" field.
func TurnIDHasPrefix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasPrefix(FieldTurnID, v))
}

// TurnIDHasSuffix applies the HasSuffix predicate on the "turn_id" field.
func TurnIDHasSuffix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasSuffix(FieldTurnID, v))
}

// TurnIDEqualFold applies the EqualFold predicate on the "turn_id" field.
func TurnIDEqualFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldTurnID, v))
}

// TurnIDContainsFold applies the ContainsFold predicate on the "turn_id" field.
func TurnIDContainsFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldTurnID, v))
}

// RuntimeEQ applies the EQ predicate on the "runtime" field.
func RuntimeEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldRuntime, v))
}

// RuntimeNEQ applies the NEQ predicate on the "runtime" field.
func RuntimeNEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldRuntime, v))
}

// RuntimeIn applies the In predicate on the "runtime" field.
func RuntimeIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldRuntime, vs...))
}

// RuntimeNotIn applies the NotIn predicate on the "runtime" field.
func RuntimeNotIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldRuntime, vs...))
}

// RuntimeGT applies the GT predicate on the "runtime" field.
func RuntimeGT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldRuntime, v))
}

// RuntimeGTE applies the GTE predicate on the "runtime" field.
func RuntimeGTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldRuntime, v))
}

// RuntimeLT applies the LT predicate on the "runtime" field.
func RuntimeLT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldRuntime, v))
}

// RuntimeLTE applies the LTE predicate on the "runtime" field.
func RuntimeLTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldRuntime, v))
}

// RuntimeContains applies the Contains predicate on the "runtime" field.
func RuntimeContains(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContains(FieldRuntime, v))
}

// RuntimeHasPrefix applies the HasPrefix predicate on the "runtime" field.
func RuntimeHasPrefix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasPrefix(FieldRuntime, v))
}

// RuntimeHasSuffix applies the HasSuffix predicate on the "runtime" field.
func RuntimeHasSuffix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasSuffix(FieldRuntime, v))
}

// RuntimeEqualFold applies the EqualFold predicate on the "runtime" field.
func RuntimeEqualFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldRuntime, v))
}

// RuntimeContainsFold applies the ContainsFold predicate on the "runtime" field.
func RuntimeContainsFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldRuntime, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldModel, v))
}

// SandboxBackendEQ applies the EQ predicate on the "sandbox_backend" field.
func SandboxBackendEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldSandboxBackend, v))
}

// SandboxBackendNEQ applies the NEQ predicate on the "sandbox_backend" field.
func SandboxBackendNEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldSandboxBackend, v))
}

// SandboxBackendIn applies the In predicate on the "sandbox_backend" field.
func SandboxBackendIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldSandboxBackend, vs...))
}

// SandboxBackendNotIn applies the NotIn predicate on the "sandbox_backend" field.
func SandboxBackendNotIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldSandboxBackend, vs...))
}

// SandboxBackendGT applies the GT predicate on the "sandbox_backend" field.
func SandboxBackendGT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldSandboxBackend, v))
}

// SandboxBackendGTE applies the GTE predicate on the "sandbox_backend" field.
func SandboxBackendGTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldSandboxBackend, v))
}

// SandboxBackendLT applies the LT predicate on the "sandbox_backend" field.
func SandboxBackendLT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldSandboxBackend, v))
}

// SandboxBackendLTE applies the LTE predicate on the "sandbox_backend" field.
func SandboxBackendLTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldSandboxBackend, v))
}

// SandboxBackendContains applies the Contains predicate on the "sandbox_backend" field.
func SandboxBackendContains(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContains(FieldSandboxBackend, v))
}

// SandboxBackendHasPrefix applies the HasPrefix predicate on the "sandbox_backend" field.
func SandboxBackendHasPrefix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasPrefix(FieldSandboxBackend, v))
}

// SandboxBackendHasSuffix applies the HasSuffix predicate on the "sandbox_backend" field.
func SandboxBackendHasSuffix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasSuffix(FieldSandboxBackend, v))
}

// SandboxBackendEqualFold applies the EqualFold predicate on the "sandbox_backend" field.
func SandboxBackendEqualFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldSandboxBackend, v))
}

// SandboxBackendContainsFold applies the ContainsFold predicate on the "sandbox_backend" field.
func SandboxBackendContainsFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldSandboxBackend, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldStatus, v))
}

// ExitCodeEQ applies the EQ predicate on the "exit_code" field.
func ExitCodeEQ(v int) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldExitCode, v))
}

// ExitCodeNEQ applies the NEQ predicate on the "exit_code" field.
func ExitCodeNEQ(v int) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldExitCode, v))
}

// ExitCodeIn applies the In predicate on the "exit_code" field.
func ExitCodeIn(vs ...int) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldExitCode, vs...))
}

// ExitCodeNotIn applies the NotIn predicate on the "exit_code" field.
func ExitCodeNotIn(vs ...int) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldExitCode, vs...))
}

// ExitCodeGT applies the GT predicate on the "exit_code" field.
func ExitCodeGT(v int) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldExitCode, v))
}

// ExitCodeGTE applies the GTE predicate on the "exit_code" field.
func ExitCodeGTE(v int) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldExitCode, v))
}

// ExitCodeLT applies the LT predicate on the "exit_code" field.
func ExitCodeLT(v int) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldExitCode, v))
}

// ExitCodeLTE applies the LTE predicate on the "exit_code" field.
func ExitCodeLTE(v int) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldExitCode, v))
}

// ExitCodeIsNil applies the IsNil predicate on the "exit_code" field.
func ExitCodeIsNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldIsNull(FieldExitCode))
}

// ExitCodeNotNil applies the NotNil predicate on the "exit_code" field.
func ExitCodeNotNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldNotNull(FieldExitCode))
}

// NativeIDEQ applies the EQ predicate on the "native_id" field.
func NativeIDEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldNativeID, v))
}

// NativeIDNEQ applies the NEQ predicate on the "native_id" field.
func NativeIDNEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldNativeID, v))
}

// NativeIDIn applies the In predicate on the "native_id" field.
func NativeIDIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldNativeID, vs...))
}

// NativeIDNotIn applies the NotIn predicate on the "native_id" field.
func NativeIDNotIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldNativeID, vs...))
}

// NativeIDGT applies the GT predicate on the "native_id" field.
func NativeIDGT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldNativeID, v))
}

// NativeIDGTE applies the GTE predicate on the "native_id" field.
func NativeIDGTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldNativeID, v))
}

// NativeIDLT applies the LT predicate on the "native_id" field.
func NativeIDLT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldNativeID, v))
}

// NativeIDLTE applies the LTE predicate on the "native_id" field.
func NativeIDLTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldNativeID, v))
}

// NativeIDContains applies the Contains predicate on the "native_id" field.
func NativeIDContains(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContains(FieldNativeID, v))
}

// NativeIDHasPrefix applies the HasPrefix predicate on the "native_id" field.
func NativeIDHasPrefix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasPrefix(FieldNativeID, v))
}

// NativeIDHasSuffix applies the HasSuffix predicate on the "native_id" field.
func NativeIDHasSuffix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasSuffix(FieldNativeID, v))
}

// NativeIDIsNil applies the IsNil predicate on the "native_id" field.
func NativeIDIsNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldIsNull(FieldNativeID))
}

// NativeIDNotNil applies the NotNil predicate on the "native_id" field.
func NativeIDNotNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldNotNull(FieldNativeID))
}

// NativeIDEqualFold applies the EqualFold predicate on the "native_id" field.
func NativeIDEqualFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldNativeID, v))
}

// NativeIDContainsFold applies the ContainsFold predicate on the "native_id" field.
func NativeIDContainsFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldNativeID, v))
}

// LogPathEQ applies the EQ predicate on the "log_path" field.
func LogPathEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldLogPath, v))
}

// LogPathNEQ applies the NEQ predicate on the "log_path" field.
func LogPathNEQ(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldLogPath, v))
}

// LogPathIn applies the In predicate on the "log_path" field.
func LogPathIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldLogPath, vs...))
}

// LogPathNotIn applies the NotIn predicate on the "log_path" field.
func LogPathNotIn(vs ...string) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldLogPath, vs...))
}

// LogPathGT applies the GT predicate on the "log_path" field.
func LogPathGT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldLogPath, v))
}

// LogPathGTE applies the GTE predicate on the "log_path" field.
func LogPathGTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldLogPath, v))
}

// LogPathLT applies the LT predicate on the "log_path" field.
func LogPathLT(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldLogPath, v))
}

// LogPathLTE applies the LTE predicate on the "log_path" field.
func LogPathLTE(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldLogPath, v))
}

// LogPathContains applies the Contains predicate on the "log_path" field.
func LogPathContains(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContains(FieldLogPath, v))
}

// LogPathHasPrefix applies the HasPrefix predicate on the "log_path" field.
func LogPathHasPrefix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasPrefix(FieldLogPath, v))
}

// LogPathHasSuffix applies the HasSuffix predicate on the "log_path" field.
func LogPathHasSuffix(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldHasSuffix(FieldLogPath, v))
}

// LogPathIsNil applies the IsNil predicate on the "log_path" field.
func LogPathIsNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldIsNull(FieldLogPath))
}

// LogPathNotNil applies the NotNil predicate on the "log_path" field.
func LogPathNotNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldNotNull(FieldLogPath))
}

// LogPathEqualFold applies the EqualFold predicate on the "log_path" field.
func LogPathEqualFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldEqualFold(FieldLogPath, v))
}

// LogPathContainsFold applies the ContainsFold predicate on the "log_path" field.
func LogPathContainsFold(v string) predicate.Invocation {
	return predicate.Invocation(sql.FieldContainsFold(FieldLogPath, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v float64) predicate.Invocation {
	return predicate.Invocation(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.Invocation {
	return predicate.Invocation(sql.FieldNotNull(FieldEndedAt))
}

// HasTurn applies the HasEdge predicate on the "turn" edge.
func HasTurn() predicate.Invocation {
	return predicate.Invocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TurnTable, TurnColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTurnWith applies the HasEdge predicate on the "turn" edge with a given conditions (other predicates).
func HasTurnWith(preds ...predicate.Turn) predicate.Invocation {
	return predicate.Invocation(func(s *sql.Selector) {
		step := newTurnStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Invocation) predicate.Invocation {
	return predicate.Invocation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Invocation) predicate.Invocation {
	return predicate.Invocation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Invocation) predicate.Invocation {
	return predicate.Invocation(sql.NotPredicates(p))
}
