-- Ent schema baseline. Change it only by adding a new numbered migration.
CREATE TABLE `candidates` (`id` text NOT NULL, `vector` text NOT NULL, `digest` text NOT NULL, `checks` text NOT NULL, `deliverables` text NOT NULL DEFAULT ('[]'), `status` text NOT NULL, `created_at` real NOT NULL, `task_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `candidates_tasks_candidates` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE NO ACTION);
CREATE TABLE `checkpoints` (`id` text NOT NULL, `archive_path` text NOT NULL, `metadata` text NOT NULL, `created_at` real NOT NULL, `session_id` text NOT NULL, `task_id` text NULL, PRIMARY KEY (`id`), CONSTRAINT `checkpoints_sessions_checkpoints` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE NO ACTION, CONSTRAINT `checkpoints_tasks_checkpoints` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE SET NULL);
CREATE TABLE `events` (`sequence` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `type` text NOT NULL, `payload` text NOT NULL, `created_at` real NOT NULL, `session_id` text NOT NULL, `task_id` text NULL, CONSTRAINT `events_sessions_events` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE NO ACTION, CONSTRAINT `events_tasks_events` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE SET NULL);
CREATE TABLE `invocations` (`id` text NOT NULL, `runtime` text NOT NULL, `model` text NOT NULL, `sandbox_backend` text NOT NULL, `status` text NOT NULL, `exit_code` integer NULL, `native_id` text NULL, `log_path` text NULL, `started_at` real NOT NULL, `ended_at` real NULL, `turn_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `invocations_turns_invocations` FOREIGN KEY (`turn_id`) REFERENCES `turns` (`id`) ON DELETE NO ACTION);
CREATE TABLE `sessions` (`id` text NOT NULL, `spec` text NOT NULL, `environment` text NOT NULL, `idempotency_key` text NULL, `creation_digest` text NULL, `environment_digest` text NOT NULL, `workspace` text NOT NULL, `status` text NOT NULL, `native_id` text NULL, `created_at` real NOT NULL, `completed_at` real NULL, `cancelled_at` real NULL, `cancel_reason` text NULL, `parent_session_id` text NULL, `parent_task_id` text NULL, `parent_invocation_id` text NULL, `delegate_agent_id` text NULL, `delegation_request_digest` text NULL, PRIMARY KEY (`id`));
CREATE UNIQUE INDEX `session_idempotency_key` ON `sessions` (`idempotency_key`);
CREATE INDEX `session_parent_task_id` ON `sessions` (`parent_task_id`);
CREATE TABLE `tasks` (`id` text NOT NULL, `sequence` integer NOT NULL, `idempotency_key` text NOT NULL, `spec` text NOT NULL, `spec_digest` text NOT NULL, `status` text NOT NULL, `candidate_id` text NULL, `error_code` text NULL, `created_at` real NOT NULL, `session_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `tasks_sessions_tasks` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX `task_session_id_idempotency_key` ON `tasks` (`session_id`, `idempotency_key`);
CREATE UNIQUE INDEX `task_session_id_sequence` ON `tasks` (`session_id`, `sequence`);
CREATE TABLE `task_bases` (`id` text NOT NULL, `repo_id` text NOT NULL, `base_commit` text NOT NULL, `task_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `task_bases_tasks_bases` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX `taskbase_task_id_repo_id` ON `task_bases` (`task_id`, `repo_id`);
CREATE TABLE `turns` (`id` text NOT NULL, `sequence` integer NOT NULL, `input` text NOT NULL, `status` text NOT NULL, `invocation_id` text NULL, `created_at` real NOT NULL, `task_id` text NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `turns_tasks_turns` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX `turn_task_id_sequence` ON `turns` (`task_id`, `sequence`);
