// Code generated by ent, DO NOT EDIT.

package checkpoint

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldSessionID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldTaskID, v))
}

// ArchivePath applies equality check predicate on the "archive_path" field. It's identical to ArchivePathEQ.
func ArchivePath(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldArchivePath, v))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldMetadata, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldCreatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContainsFold(FieldSessionID, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotNull(FieldTaskID))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContainsFold(FieldTaskID, v))
}

// ArchivePathEQ applies the EQ predicate on the "archive_path" field.
func ArchivePathEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldArchivePath, v))
}

// ArchivePathNEQ applies the NEQ predicate on the "archive_path" field.
func ArchivePathNEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldArchivePath, v))
}

// ArchivePathIn applies the In predicate on the "archive_path" field.
func ArchivePathIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldArchivePath, vs...))
}

// ArchivePathNotIn applies the NotIn predicate on the "archive_path" field.
func ArchivePathNotIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldArchivePath, vs...))
}

// ArchivePathGT applies the GT predicate on the "archive_path" field.
func ArchivePathGT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldArchivePath, v))
}

// ArchivePathGTE applies the GTE predicate on the "archive_path" field.
func ArchivePathGTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldArchivePath, v))
}

// ArchivePathLT applies the LT predicate on the "archive_path" field.
func ArchivePathLT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldArchivePath, v))
}

// ArchivePathLTE applies the LTE predicate on the "archive_path" field.
func ArchivePathLTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldArchivePath, v))
}

// ArchivePathContains applies the Contains predicate on the "archive_path" field.
func ArchivePathContains(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContains(FieldArchivePath, v))
}

// ArchivePathHasPrefix applies the HasPrefix predicate on the "archive_path" field.
func ArchivePathHasPrefix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasPrefix(FieldArchivePath, v))
}

// ArchivePathHasSuffix applies the HasSuffix predicate on the "archive_path" field.
func ArchivePathHasSuffix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasSuffix(FieldArchivePath, v))
}

// ArchivePathEqualFold applies the EqualFold predicate on the "archive_path" field.
func ArchivePathEqualFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEqualFold(FieldArchivePath, v))
}

// ArchivePathContainsFold applies the ContainsFold predicate on the "archive_path" field.
func ArchivePathContainsFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContainsFold(FieldArchivePath, v))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldMetadata, v))
}

// MetadataContains applies the Contains predicate on the "metadata" field.
func MetadataContains(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContains(FieldMetadata, v))
}

// MetadataHasPrefix applies the HasPrefix predicate on the "metadata" field.
func MetadataHasPrefix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasPrefix(FieldMetadata, v))
}

// MetadataHasSuffix applies the HasSuffix predicate on the "metadata" field.
func MetadataHasSuffix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasSuffix(FieldMetadata, v))
}

// MetadataEqualFold applies the EqualFold predicate on the "metadata" field.
func MetadataEqualFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEqualFold(FieldMetadata, v))
}

// MetadataContainsFold applies the ContainsFold predicate on the "metadata" field.
func MetadataContainsFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContainsFold(FieldMetadata, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v float64) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Checkpoint) predicate.Checkpoint {
	return predicate.Checkpoint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Checkpoint) predicate.Checkpoint {
	return predicate.Checkpoint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Checkpoint) predicate.Checkpoint {
	return predicate.Checkpoint(sql.NotPredicates(p))
}
