// Code generated by ent, DO NOT EDIT.

package task

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldSpec holds the string denoting the spec field in the database.
	FieldSpec = "spec"
	// FieldSpecDigest holds the string denoting the spec_digest field in the database.
	FieldSpecDigest = "spec_digest"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCandidateID holds the string denoting the candidate_id field in the database.
	FieldCandidateID = "candidate_id"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeTurns holds the string denoting the turns edge name in mutations.
	EdgeTurns = "turns"
	// EdgeCandidates holds the string denoting the candidates edge name in mutations.
	EdgeCandidates = "candidates"
	// EdgeBases holds the string denoting the bases edge name in mutations.
	EdgeBases = "bases"
	// EdgeCheckpoints holds the string denoting the checkpoints edge name in mutations.
	EdgeCheckpoints = "checkpoints"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EventFieldID holds the string denoting the ID field of the Event.
	EventFieldID = "sequence"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "tasks"
	// SessionInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionInverseTable = "sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
	// TurnsTable is the table that holds the turns relation/edge.
	TurnsTable = "turns"
	// TurnsInverseTable is the table name for the Turn entity.
	// It exists in this package in order to avoid circular dependency with the "turn" package.
	TurnsInverseTable = "turns"
	// TurnsColumn is the table column denoting the turns relation/edge.
	TurnsColumn = "task_id"
	// CandidatesTable is the table that holds the candidates relation/edge.
	CandidatesTable = "candidates"
	// CandidatesInverseTable is the table name for the Candidate entity.
	// It exists in this package in order to avoid circular dependency with the "candidate" package.
	CandidatesInverseTable = "candidates"
	// CandidatesColumn is the table column denoting the candidates relation/edge.
	CandidatesColumn = "task_id"
	// BasesTable is the table that holds the bases relation/edge.
	BasesTable = "task_bases"
	// BasesInverseTable is the table name for the TaskBase entity.
	// It exists in this package in order to avoid circular dependency with the "taskbase" package.
	BasesInverseTable = "task_bases"
	// BasesColumn is the table column denoting the bases relation/edge.
	BasesColumn = "task_id"
	// CheckpointsTable is the table that holds the checkpoints relation/edge.
	CheckpointsTable = "checkpoints"
	// CheckpointsInverseTable is the table name for the Checkpoint entity.
	// It exists in this package in order to avoid circular dependency with the "checkpoint" package.
	CheckpointsInverseTable = "checkpoints"
	// CheckpointsColumn is the table column denoting the checkpoints relation/edge.
	CheckpointsColumn = "task_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "task_id"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldSequence,
	FieldIdempotencyKey,
	FieldSpec,
	FieldSpecDigest,
	FieldStatus,
	FieldCandidateID,
	FieldErrorCode,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// BySpec orders the results by the spec field.
func BySpec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpec, opts...).ToFunc()
}

// BySpecDigest orders the results by the spec_digest field.
func BySpecDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecDigest, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCandidateID orders the results by the candidate_id field.
func ByCandidateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCandidateID, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByTurnsCount orders the results by turns count.
func ByTurnsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTurnsStep(), opts...)
	}
}

// ByTurns orders the results by turns terms.
func ByTurns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTurnsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCandidatesCount orders the results by candidates count.
func ByCandidatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCandidatesStep(), opts...)
	}
}

// ByCandidates orders the results by candidates terms.
func ByCandidates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCandidatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBasesCount orders the results by bases count.
func ByBasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBasesStep(), opts...)
	}
}

// ByBases orders the results by bases terms.
func ByBases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCheckpointsCount orders the results by checkpoints count.
func ByCheckpointsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCheckpointsStep(), opts...)
	}
}

// ByCheckpoints orders the results by checkpoints terms.
func ByCheckpoints(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckpointsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newTurnsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TurnsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TurnsTable, TurnsColumn),
	)
}
func newCandidatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CandidatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CandidatesTable, CandidatesColumn),
	)
}
func newBasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BasesTable, BasesColumn),
	)
}
func newCheckpointsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckpointsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CheckpointsTable, CheckpointsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, EventFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
