// Code generated by ent, DO NOT EDIT.

package session

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpec holds the string denoting the spec field in the database.
	FieldSpec = "spec"
	// FieldEnvironment holds the string denoting the environment field in the database.
	FieldEnvironment = "environment"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldCreationDigest holds the string denoting the creation_digest field in the database.
	FieldCreationDigest = "creation_digest"
	// FieldEnvironmentDigest holds the string denoting the environment_digest field in the database.
	FieldEnvironmentDigest = "environment_digest"
	// FieldWorkspace holds the string denoting the workspace field in the database.
	FieldWorkspace = "workspace"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNativeID holds the string denoting the native_id field in the database.
	FieldNativeID = "native_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCancelledAt holds the string denoting the cancelled_at field in the database.
	FieldCancelledAt = "cancelled_at"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldParentSessionID holds the string denoting the parent_session_id field in the database.
	FieldParentSessionID = "parent_session_id"
	// FieldParentTaskID holds the string denoting the parent_task_id field in the database.
	FieldParentTaskID = "parent_task_id"
	// FieldParentInvocationID holds the string denoting the parent_invocation_id field in the database.
	FieldParentInvocationID = "parent_invocation_id"
	// FieldDelegateAgentID holds the string denoting the delegate_agent_id field in the database.
	FieldDelegateAgentID = "delegate_agent_id"
	// FieldDelegationRequestDigest holds the string denoting the delegation_request_digest field in the database.
	FieldDelegationRequestDigest = "delegation_request_digest"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// EdgeCheckpoints holds the string denoting the checkpoints edge name in mutations.
	EdgeCheckpoints = "checkpoints"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EventFieldID holds the string denoting the ID field of the Event.
	EventFieldID = "sequence"
	// Table holds the table name of the session in the database.
	Table = "sessions"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "tasks"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "session_id"
	// CheckpointsTable is the table that holds the checkpoints relation/edge.
	CheckpointsTable = "checkpoints"
	// CheckpointsInverseTable is the table name for the Checkpoint entity.
	// It exists in this package in order to avoid circular dependency with the "checkpoint" package.
	CheckpointsInverseTable = "checkpoints"
	// CheckpointsColumn is the table column denoting the checkpoints relation/edge.
	CheckpointsColumn = "session_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "session_id"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldSpec,
	FieldEnvironment,
	FieldIdempotencyKey,
	FieldCreationDigest,
	FieldEnvironmentDigest,
	FieldWorkspace,
	FieldStatus,
	FieldNativeID,
	FieldCreatedAt,
	FieldCompletedAt,
	FieldCancelledAt,
	FieldCancelReason,
	FieldParentSessionID,
	FieldParentTaskID,
	FieldParentInvocationID,
	FieldDelegateAgentID,
	FieldDelegationRequestDigest,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Session queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpec orders the results by the spec field.
func BySpec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpec, opts...).ToFunc()
}

// ByEnvironment orders the results by the environment field.
func ByEnvironment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironment, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByCreationDigest orders the results by the creation_digest field.
func ByCreationDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreationDigest, opts...).ToFunc()
}

// ByEnvironmentDigest orders the results by the environment_digest field.
func ByEnvironmentDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentDigest, opts...).ToFunc()
}

// ByWorkspace orders the results by the workspace field.
func ByWorkspace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspace, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNativeID orders the results by the native_id field.
func ByNativeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNativeID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCancelledAt orders the results by the cancelled_at field.
func ByCancelledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledAt, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByParentSessionID orders the results by the parent_session_id field.
func ByParentSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentSessionID, opts...).ToFunc()
}

// ByParentTaskID orders the results by the parent_task_id field.
func ByParentTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentTaskID, opts...).ToFunc()
}

// ByParentInvocationID orders the results by the parent_invocation_id field.
func ByParentInvocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentInvocationID, opts...).ToFunc()
}

// ByDelegateAgentID orders the results by the delegate_agent_id field.
func ByDelegateAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelegateAgentID, opts...).ToFunc()
}

// ByDelegationRequestDigest orders the results by the delegation_request_digest field.
func ByDelegationRequestDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelegationRequestDigest, opts...).ToFunc()
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCheckpointsCount orders the results by checkpoints count.
func ByCheckpointsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCheckpointsStep(), opts...)
	}
}

// ByCheckpoints orders the results by checkpoints terms.
func ByCheckpoints(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckpointsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
func newCheckpointsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckpointsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CheckpointsTable, CheckpointsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, EventFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
