// Code generated by ent, DO NOT EDIT.

package session

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Covalane/turnyard/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldID, id))
}

// Spec applies equality check predicate on the "spec" field. It's identical to SpecEQ.
func Spec(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSpec, v))
}

// Environment applies equality check predicate on the "environment" field. It's identical to EnvironmentEQ.
func Environment(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEnvironment, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIdempotencyKey, v))
}

// CreationDigest applies equality check predicate on the "creation_digest" field. It's identical to CreationDigestEQ.
func CreationDigest(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreationDigest, v))
}

// EnvironmentDigest applies equality check predicate on the "environment_digest" field. It's identical to EnvironmentDigestEQ.
func EnvironmentDigest(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEnvironmentDigest, v))
}

// Workspace applies equality check predicate on the "workspace" field. It's identical to WorkspaceEQ.
func Workspace(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldWorkspace, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStatus, v))
}

// NativeID applies equality check predicate on the "native_id" field. It's identical to NativeIDEQ.
func NativeID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldNativeID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCompletedAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelReason applies equality check predicate on the "cancel_reason" field. It's identical to CancelReasonEQ.
func CancelReason(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCancelReason, v))
}

// ParentSessionID applies equality check predicate on the "parent_session_id" field. It's identical to ParentSessionIDEQ.
func ParentSessionID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentSessionID, v))
}

// ParentTaskID applies equality check predicate on the "parent_task_id" field. It's identical to ParentTaskIDEQ.
func ParentTaskID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentTaskID, v))
}

// ParentInvocationID applies equality check predicate on the "parent_invocation_id" field. It's identical to ParentInvocationIDEQ.
func ParentInvocationID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentInvocationID, v))
}

// DelegateAgentID applies equality check predicate on the "delegate_agent_id" field. It's identical to DelegateAgentIDEQ.
func DelegateAgentID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldDelegateAgentID, v))
}

// DelegationRequestDigest applies equality check predicate on the "delegation_request_digest" field. It's identical to DelegationRequestDigestEQ.
func DelegationRequestDigest(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldDelegationRequestDigest, v))
}

// SpecEQ applies the EQ predicate on the "spec" field.
func SpecEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSpec, v))
}

// SpecNEQ applies the NEQ predicate on the "spec" field.
func SpecNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldSpec, v))
}

// SpecIn applies the In predicate on the "spec" field.
func SpecIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldSpec, vs...))
}

// SpecNotIn applies the NotIn predicate on the "spec" field.
func SpecNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldSpec, vs...))
}

// SpecGT applies the GT predicate on the "spec" field.
func SpecGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldSpec, v))
}

// SpecGTE applies the GTE predicate on the "spec" field.
func SpecGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldSpec, v))
}

// SpecLT applies the LT predicate on the "spec" field.
func SpecLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldSpec, v))
}

// SpecLTE applies the LTE predicate on the "spec" field.
func SpecLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldSpec, v))
}

// SpecContains applies the Contains predicate on the "spec" field.
func SpecContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldSpec, v))
}

// SpecHasPrefix applies the HasPrefix predicate on the "spec" field.
func SpecHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldSpec, v))
}

// SpecHasSuffix applies the HasSuffix predicate on the "spec" field.
func SpecHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldSpec, v))
}

// SpecEqualFold applies the EqualFold predicate on the "spec" field.
func SpecEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldSpec, v))
}

// SpecContainsFold applies the ContainsFold predicate on the "spec" field.
func SpecContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldSpec, v))
}

// EnvironmentEQ applies the EQ predicate on the "environment" field.
func EnvironmentEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEnvironment, v))
}

// EnvironmentNEQ applies the NEQ predicate on the "environment" field.
func EnvironmentNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldEnvironment, v))
}

// EnvironmentIn applies the In predicate on the "environment" field.
func EnvironmentIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldEnvironment, vs...))
}

// EnvironmentNotIn applies the NotIn predicate on the "environment" field.
func EnvironmentNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldEnvironment, vs...))
}

// EnvironmentGT applies the GT predicate on the "environment" field.
func EnvironmentGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldEnvironment, v))
}

// EnvironmentGTE applies the GTE predicate on the "environment" field.
func EnvironmentGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldEnvironment, v))
}

// EnvironmentLT applies the LT predicate on the "environment" field.
func EnvironmentLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldEnvironment, v))
}

// EnvironmentLTE applies the LTE predicate on the "environment" field.
func EnvironmentLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldEnvironment, v))
}

// EnvironmentContains applies the Contains predicate on the "environment" field.
func EnvironmentContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldEnvironment, v))
}

// EnvironmentHasPrefix applies the HasPrefix predicate on the "environment" field.
func EnvironmentHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldEnvironment, v))
}

// EnvironmentHasSuffix applies the HasSuffix predicate on the "environment" field.
func EnvironmentHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldEnvironment, v))
}

// EnvironmentEqualFold applies the EqualFold predicate on the "environment" field.
func EnvironmentEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldEnvironment, v))
}

// EnvironmentContainsFold applies the ContainsFold predicate on the "environment" field.
func EnvironmentContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldEnvironment, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// CreationDigestEQ applies the EQ predicate on the "creation_digest" field.
func CreationDigestEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreationDigest, v))
}

// CreationDigestNEQ applies the NEQ predicate on the "creation_digest" field.
func CreationDigestNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCreationDigest, v))
}

// CreationDigestIn applies the In predicate on the "creation_digest" field.
func CreationDigestIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCreationDigest, vs...))
}

// CreationDigestNotIn applies the NotIn predicate on the "creation_digest" field.
func CreationDigestNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCreationDigest, vs...))
}

// CreationDigestGT applies the GT predicate on the "creation_digest" field.
func CreationDigestGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCreationDigest, v))
}

// CreationDigestGTE applies the GTE predicate on the "creation_digest" field.
func CreationDigestGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCreationDigest, v))
}

// CreationDigestLT applies the LT predicate on the "creation_digest" field.
func CreationDigestLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCreationDigest, v))
}

// CreationDigestLTE applies the LTE predicate on the "creation_digest" field.
func CreationDigestLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCreationDigest, v))
}

// CreationDigestContains applies the Contains predicate on the "creation_digest" field.
func CreationDigestContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldCreationDigest, v))
}

// CreationDigestHasPrefix applies the HasPrefix predicate on the "creation_digest" field.
func CreationDigestHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldCreationDigest, v))
}

// CreationDigestHasSuffix applies the HasSuffix predicate on the "creation_digest" field.
func CreationDigestHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldCreationDigest, v))
}

// CreationDigestIsNil applies the IsNil predicate on the "creation_digest" field.
func CreationDigestIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldCreationDigest))
}

// CreationDigestNotNil applies the NotNil predicate on the "creation_digest" field.
func CreationDigestNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldCreationDigest))
}

// CreationDigestEqualFold applies the EqualFold predicate on the "creation_digest" field.
func CreationDigestEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldCreationDigest, v))
}

// CreationDigestContainsFold applies the ContainsFold predicate on the "creation_digest" field.
func CreationDigestContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldCreationDigest, v))
}

// EnvironmentDigestEQ applies the EQ predicate on the "environment_digest" field.
func EnvironmentDigestEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEnvironmentDigest, v))
}

// EnvironmentDigestNEQ applies the NEQ predicate on the "environment_digest" field.
func EnvironmentDigestNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldEnvironmentDigest, v))
}

// EnvironmentDigestIn applies the In predicate on the "environment_digest" field.
func EnvironmentDigestIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldEnvironmentDigest, vs...))
}

// EnvironmentDigestNotIn applies the NotIn predicate on the "environment_digest" field.
func EnvironmentDigestNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldEnvironmentDigest, vs...))
}

// EnvironmentDigestGT applies the GT predicate on the "environment_digest" field.
func EnvironmentDigestGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldEnvironmentDigest, v))
}

// EnvironmentDigestGTE applies the GTE predicate on the "environment_digest" field.
func EnvironmentDigestGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldEnvironmentDigest, v))
}

// EnvironmentDigestLT applies the LT predicate on the "environment_digest" field.
func EnvironmentDigestLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldEnvironmentDigest, v))
}

// EnvironmentDigestLTE applies the LTE predicate on the "environment_digest" field.
func EnvironmentDigestLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldEnvironmentDigest, v))
}

// EnvironmentDigestContains applies the Contains predicate on the "environment_digest" field.
func EnvironmentDigestContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldEnvironmentDigest, v))
}

// EnvironmentDigestHasPrefix applies the HasPrefix predicate on the "environment_digest" field.
func EnvironmentDigestHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldEnvironmentDigest, v))
}

// EnvironmentDigestHasSuffix applies the HasSuffix predicate on the "environment_digest" field.
func EnvironmentDigestHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldEnvironmentDigest, v))
}

// EnvironmentDigestEqualFold applies the EqualFold predicate on the "environment_digest" field.
func EnvironmentDigestEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldEnvironmentDigest, v))
}

// EnvironmentDigestContainsFold applies the ContainsFold predicate on the "environment_digest" field.
func EnvironmentDigestContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldEnvironmentDigest, v))
}

// WorkspaceEQ applies the EQ predicate on the "workspace" field.
func WorkspaceEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldWorkspace, v))
}

// WorkspaceNEQ applies the NEQ predicate on the "workspace" field.
func WorkspaceNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldWorkspace, v))
}

// WorkspaceIn applies the In predicate on the "workspace" field.
func WorkspaceIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldWorkspace, vs...))
}

// WorkspaceNotIn applies the NotIn predicate on the "workspace" field.
func WorkspaceNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldWorkspace, vs...))
}

// WorkspaceGT applies the GT predicate on the "workspace" field.
func WorkspaceGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldWorkspace, v))
}

// WorkspaceGTE applies the GTE predicate on the "workspace" field.
func WorkspaceGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldWorkspace, v))
}

// WorkspaceLT applies the LT predicate on the "workspace" field.
func WorkspaceLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldWorkspace, v))
}

// WorkspaceLTE applies the LTE predicate on the "workspace" field.
func WorkspaceLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldWorkspace, v))
}

// WorkspaceContains applies the Contains predicate on the "workspace" field.
func WorkspaceContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldWorkspace, v))
}

// WorkspaceHasPrefix applies the HasPrefix predicate on the "workspace" field.
func WorkspaceHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldWorkspace, v))
}

// WorkspaceHasSuffix applies the HasSuffix predicate on the "workspace" field.
func WorkspaceHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldWorkspace, v))
}

// WorkspaceEqualFold applies the EqualFold predicate on the "workspace" field.
func WorkspaceEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldWorkspace, v))
}

// WorkspaceContainsFold applies the ContainsFold predicate on the "workspace" field.
func WorkspaceContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldWorkspace, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldStatus, v))
}

// NativeIDEQ applies the EQ predicate on the "native_id" field.
func NativeIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldNativeID, v))
}

// NativeIDNEQ applies the NEQ predicate on the "native_id" field.
func NativeIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldNativeID, v))
}

// NativeIDIn applies the In predicate on the "native_id" field.
func NativeIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldNativeID, vs...))
}

// NativeIDNotIn applies the NotIn predicate on the "native_id" field.
func NativeIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldNativeID, vs...))
}

// NativeIDGT applies the GT predicate on the "native_id" field.
func NativeIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldNativeID, v))
}

// NativeIDGTE applies the GTE predicate on the "native_id" field.
func NativeIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldNativeID, v))
}

// NativeIDLT applies the LT predicate on the "native_id" field.
func NativeIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldNativeID, v))
}

// NativeIDLTE applies the LTE predicate on the "native_id" field.
func NativeIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldNativeID, v))
}

// NativeIDContains applies the Contains predicate on the "native_id" field.
func NativeIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldNativeID, v))
}

// NativeIDHasPrefix applies the HasPrefix predicate on the "native_id" field.
func NativeIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldNativeID, v))
}

// NativeIDHasSuffix applies the HasSuffix predicate on the "native_id" field.
func NativeIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldNativeID, v))
}

// NativeIDIsNil applies the IsNil predicate on the "native_id" field.
func NativeIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldNativeID))
}

// NativeIDNotNil applies the NotNil predicate on the "native_id" field.
func NativeIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldNativeID))
}

// NativeIDEqualFold applies the EqualFold predicate on the "native_id" field.
func NativeIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldNativeID, v))
}

// NativeIDContainsFold applies the ContainsFold predicate on the "native_id" field.
func NativeIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldNativeID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v float64) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v float64) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCreatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v float64) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v float64) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldCompletedAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v float64) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v float64) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldCancelledAt))
}

// CancelReasonEQ applies the EQ predicate on the "cancel_reason" field.
func CancelReasonEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCancelReason, v))
}

// CancelReasonNEQ applies the NEQ predicate on the "cancel_reason" field.
func CancelReasonNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCancelReason, v))
}

// CancelReasonIn applies the In predicate on the "cancel_reason" field.
func CancelReasonIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCancelReason, vs...))
}

// CancelReasonNotIn applies the NotIn predicate on the "cancel_reason" field.
func CancelReasonNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCancelReason, vs...))
}

// CancelReasonGT applies the GT predicate on the "cancel_reason" field.
func CancelReasonGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCancelReason, v))
}

// CancelReasonGTE applies the GTE predicate on the "cancel_reason" field.
func CancelReasonGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCancelReason, v))
}

// CancelReasonLT applies the LT predicate on the "cancel_reason" field.
func CancelReasonLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCancelReason, v))
}

// CancelReasonLTE applies the LTE predicate on the "cancel_reason" field.
func CancelReasonLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCancelReason, v))
}

// CancelReasonContains applies the Contains predicate on the "cancel_reason" field.
func CancelReasonContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldCancelReason, v))
}

// CancelReasonHasPrefix applies the HasPrefix predicate on the "cancel_reason" field.
func CancelReasonHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldCancelReason, v))
}

// CancelReasonHasSuffix applies the HasSuffix predicate on the "cancel_reason" field.
func CancelReasonHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldCancelReason, v))
}

// CancelReasonIsNil applies the IsNil predicate on the "cancel_reason" field.
func CancelReasonIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldCancelReason))
}

// CancelReasonNotNil applies the NotNil predicate on the "cancel_reason" field.
func CancelReasonNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldCancelReason))
}

// CancelReasonEqualFold applies the EqualFold predicate on the "cancel_reason" field.
func CancelReasonEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldCancelReason, v))
}

// CancelReasonContainsFold applies the ContainsFold predicate on the "cancel_reason" field.
func CancelReasonContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldCancelReason, v))
}

// ParentSessionIDEQ applies the EQ predicate on the "parent_session_id" field.
func ParentSessionIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentSessionID, v))
}

// ParentSessionIDNEQ applies the NEQ predicate on the "parent_session_id" field.
func ParentSessionIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldParentSessionID, v))
}

// ParentSessionIDIn applies the In predicate on the "parent_session_id" field.
func ParentSessionIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldParentSessionID, vs...))
}

// ParentSessionIDNotIn applies the NotIn predicate on the "parent_session_id" field.
func ParentSessionIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldParentSessionID, vs...))
}

// ParentSessionIDGT applies the GT predicate on the "parent_session_id" field.
func ParentSessionIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldParentSessionID, v))
}

// ParentSessionIDGTE applies the GTE predicate on the "parent_session_id" field.
func ParentSessionIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldParentSessionID, v))
}

// ParentSessionIDLT applies the LT predicate on the "parent_session_id" field.
func ParentSessionIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldParentSessionID, v))
}

// ParentSessionIDLTE applies the LTE predicate on the "parent_session_id" field.
func ParentSessionIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldParentSessionID, v))
}

// ParentSessionIDContains applies the Contains predicate on the "parent_session_id" field.
func ParentSessionIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldParentSessionID, v))
}

// ParentSessionIDHasPrefix applies the HasPrefix predicate on the "parent_session_id" field.
func ParentSessionIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldParentSessionID, v))
}

// ParentSessionIDHasSuffix applies the HasSuffix predicate on the "parent_session_id" field.
func ParentSessionIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldParentSessionID, v))
}

// ParentSessionIDIsNil applies the IsNil predicate on the "parent_session_id" field.
func ParentSessionIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldParentSessionID))
}

// ParentSessionIDNotNil applies the NotNil predicate on the "parent_session_id" field.
func ParentSessionIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldParentSessionID))
}

// ParentSessionIDEqualFold applies the EqualFold predicate on the "parent_session_id" field.
func ParentSessionIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldParentSessionID, v))
}

// ParentSessionIDContainsFold applies the ContainsFold predicate on the "parent_session_id" field.
func ParentSessionIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldParentSessionID, v))
}

// ParentTaskIDEQ applies the EQ predicate on the "parent_task_id" field.
func ParentTaskIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentTaskID, v))
}

// ParentTaskIDNEQ applies the NEQ predicate on the "parent_task_id" field.
func ParentTaskIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldParentTaskID, v))
}

// ParentTaskIDIn applies the In predicate on the "parent_task_id" field.
func ParentTaskIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldParentTaskID, vs...))
}

// ParentTaskIDNotIn applies the NotIn predicate on the "parent_task_id" field.
func ParentTaskIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldParentTaskID, vs...))
}

// ParentTaskIDGT applies the GT predicate on the "parent_task_id" field.
func ParentTaskIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldParentTaskID, v))
}

// ParentTaskIDGTE applies the GTE predicate on the "parent_task_id" field.
func ParentTaskIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldParentTaskID, v))
}

// ParentTaskIDLT applies the LT predicate on the "parent_task_id" field.
func ParentTaskIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldParentTaskID, v))
}

// ParentTaskIDLTE applies the LTE predicate on the "parent_task_id" field.
func ParentTaskIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldParentTaskID, v))
}

// ParentTaskIDContains applies the Contains predicate on the "parent_task_id" field.
func ParentTaskIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldParentTaskID, v))
}

// ParentTaskIDHasPrefix applies the HasPrefix predicate on the "parent_task_id" field.
func ParentTaskIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldParentTaskID, v))
}

// ParentTaskIDHasSuffix applies the HasSuffix predicate on the "parent_task_id" field.
func ParentTaskIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldParentTaskID, v))
}

// ParentTaskIDIsNil applies the IsNil predicate on the "parent_task_id" field.
func ParentTaskIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldParentTaskID))
}

// ParentTaskIDNotNil applies the NotNil predicate on the "parent_task_id" field.
func ParentTaskIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldParentTaskID))
}

// ParentTaskIDEqualFold applies the EqualFold predicate on the "parent_task_id" field.
func ParentTaskIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldParentTaskID, v))
}

// ParentTaskIDContainsFold applies the ContainsFold predicate on the "parent_task_id" field.
func ParentTaskIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldParentTaskID, v))
}

// ParentInvocationIDEQ applies the EQ predicate on the "parent_invocation_id" field.
func ParentInvocationIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentInvocationID, v))
}

// ParentInvocationIDNEQ applies the NEQ predicate on the "parent_invocation_id" field.
func ParentInvocationIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldParentInvocationID, v))
}

// ParentInvocationIDIn applies the In predicate on the "parent_invocation_id" field.
func ParentInvocationIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldParentInvocationID, vs...))
}

// ParentInvocationIDNotIn applies the NotIn predicate on the "parent_invocation_id" field.
func ParentInvocationIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldParentInvocationID, vs...))
}

// ParentInvocationIDGT applies the GT predicate on the "parent_invocation_id" field.
func ParentInvocationIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldParentInvocationID, v))
}

// ParentInvocationIDGTE applies the GTE predicate on the "parent_invocation_id" field.
func ParentInvocationIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldParentInvocationID, v))
}

// ParentInvocationIDLT applies the LT predicate on the "parent_invocation_id" field.
func ParentInvocationIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldParentInvocationID, v))
}

// ParentInvocationIDLTE applies the LTE predicate on the "parent_invocation_id" field.
func ParentInvocationIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldParentInvocationID, v))
}

// ParentInvocationIDContains applies the Contains predicate on the "parent_invocation_id" field.
func ParentInvocationIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldParentInvocationID, v))
}

// ParentInvocationIDHasPrefix applies the HasPrefix predicate on the "parent_invocation_id" field.
func ParentInvocationIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldParentInvocationID, v))
}

// ParentInvocationIDHasSuffix applies the HasSuffix predicate on the "parent_invocation_id" field.
func ParentInvocationIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldParentInvocationID, v))
}

// ParentInvocationIDIsNil applies the IsNil predicate on the "parent_invocation_id" field.
func ParentInvocationIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldParentInvocationID))
}

// ParentInvocationIDNotNil applies the NotNil predicate on the "parent_invocation_id" field.
func ParentInvocationIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldParentInvocationID))
}

// ParentInvocationIDEqualFold applies the EqualFold predicate on the "parent_invocation_id" field.
func ParentInvocationIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldParentInvocationID, v))
}

// ParentInvocationIDContainsFold applies the ContainsFold predicate on the "parent_invocation_id" field.
func ParentInvocationIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldParentInvocationID, v))
}

// DelegateAgentIDEQ applies the EQ predicate on the "delegate_agent_id" field.
func DelegateAgentIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldDelegateAgentID, v))
}

// DelegateAgentIDNEQ applies the NEQ predicate on the "delegate_agent_id" field.
func DelegateAgentIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldDelegateAgentID, v))
}

// DelegateAgentIDIn applies the In predicate on the "delegate_agent_id" field.
func DelegateAgentIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldDelegateAgentID, vs...))
}

// DelegateAgentIDNotIn applies the NotIn predicate on the "delegate_agent_id" field.
func DelegateAgentIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldDelegateAgentID, vs...))
}

// DelegateAgentIDGT applies the GT predicate on the "delegate_agent_id" field.
func DelegateAgentIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldDelegateAgentID, v))
}

// DelegateAgentIDGTE applies the GTE predicate on the "delegate_agent_id" field.
func DelegateAgentIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldDelegateAgentID, v))
}

// DelegateAgentIDLT applies the LT predicate on the "delegate_agent_id" field.
func DelegateAgentIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldDelegateAgentID, v))
}

// DelegateAgentIDLTE applies the LTE predicate on the "delegate_agent_id" field.
func DelegateAgentIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldDelegateAgentID, v))
}

// DelegateAgentIDContains applies the Contains predicate on the "delegate_agent_id" field.
func DelegateAgentIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldDelegateAgentID, v))
}

// DelegateAgentIDHasPrefix applies the HasPrefix predicate on the "delegate_agent_id" field.
func DelegateAgentIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldDelegateAgentID, v))
}

// DelegateAgentIDHasSuffix applies the HasSuffix predicate on the "delegate_agent_id" field.
func DelegateAgentIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldDelegateAgentID, v))
}

// DelegateAgentIDIsNil applies the IsNil predicate on the "delegate_agent_id" field.
func DelegateAgentIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldDelegateAgentID))
}

// DelegateAgentIDNotNil applies the NotNil predicate on the "delegate_agent_id" field.
func DelegateAgentIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldDelegateAgentID))
}

// DelegateAgentIDEqualFold applies the EqualFold predicate on the "delegate_agent_id" field.
func DelegateAgentIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldDelegateAgentID, v))
}

// DelegateAgentIDContainsFold applies the ContainsFold predicate on the "delegate_agent_id" field.
func DelegateAgentIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldDelegateAgentID, v))
}

// DelegationRequestDigestEQ applies the EQ predicate on the "delegation_request_digest" field.
func DelegationRequestDigestEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestNEQ applies the NEQ predicate on the "delegation_request_digest" field.
func DelegationRequestDigestNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestIn applies the In predicate on the "delegation_request_digest" field.
func DelegationRequestDigestIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldDelegationRequestDigest, vs...))
}

// DelegationRequestDigestNotIn applies the NotIn predicate on the "delegation_request_digest" field.
func DelegationRequestDigestNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldDelegationRequestDigest, vs...))
}

// DelegationRequestDigestGT applies the GT predicate on the "delegation_request_digest" field.
func DelegationRequestDigestGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestGTE applies the GTE predicate on the "delegation_request_digest" field.
func DelegationRequestDigestGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestLT applies the LT predicate on the "delegation_request_digest" field.
func DelegationRequestDigestLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestLTE applies the LTE predicate on the "delegation_request_digest" field.
func DelegationRequestDigestLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestContains applies the Contains predicate on the "delegation_request_digest" field.
func DelegationRequestDigestContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestHasPrefix applies the HasPrefix predicate on the "delegation_request_digest" field.
func DelegationRequestDigestHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestHasSuffix applies the HasSuffix predicate on the "delegation_request_digest" field.
func DelegationRequestDigestHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestIsNil applies the IsNil predicate on the "delegation_request_digest" field.
func DelegationRequestDigestIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldDelegationRequestDigest))
}

// DelegationRequestDigestNotNil applies the NotNil predicate on the "delegation_request_digest" field.
func DelegationRequestDigestNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldDelegationRequestDigest))
}

// DelegationRequestDigestEqualFold applies the EqualFold predicate on the "delegation_request_digest" field.
func DelegationRequestDigestEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldDelegationRequestDigest, v))
}

// DelegationRequestDigestContainsFold applies the ContainsFold predicate on the "delegation_request_digest" field.
func DelegationRequestDigestContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldDelegationRequestDigest, v))
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.Task) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCheckpoints applies the HasEdge predicate on the "checkpoints" edge.
func HasCheckpoints() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CheckpointsTable, CheckpointsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCheckpointsWith applies the HasEdge predicate on the "checkpoints" edge with a given conditions (other predicates).
func HasCheckpointsWith(preds ...predicate.Checkpoint) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newCheckpointsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.Event) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
